type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2000": [
    { title: "AIR", score: 8.4 },
    { title: "月姬", score: 8.2 },
    { title: "幻灵镇魂曲", score: 8.2 },
    { title: "无颜之月", score: 7.2 },
    { title: "第七夜：无限轮回的终结", score: 7.2 },
  ],
  "2001": [
    { title: "家族计划", score: 8.4 },
    { title: "大恶司", score: 7.6 },
    { title: "对你说再见～comment te dire adieu～", score: 7.5 },
    { title: "秋之回忆2", score: 8.1 },
    { title: "你所期望的永远", score: 7.8 },
    { title: "鬼作", score: 7.6 },
    { title: "歌月十夜", score: 7.5 },
    { title: "水夏", score: 7.1 },
    { title: "吸血歼鬼维德戈尼亚", score: 6.7 },
  ],
  "2002": [
    { title: "时空轮回", score: 9.1 },
    { title: "腐姬", score: 8.3 },
    { title: "传颂之物", score: 7.8 },
    { title: "寒蝉鸣泣之时 鬼隐篇", score: 7.6 },
    { title: "寒蝉鸣泣之时 绵流篇", score: 8.1 },
    { title: "兰斯5D：孤单的女孩子", score: 5.7 },
  ],
  "2003": [
    { title: "CROSS†CHANNEL", score: 8.5 },
    { title: "Muv-Luv", score: 6.7 },
    { title: "沙耶之歌", score: 7.7 },
    { title: "河原崎家的一族2", score: 7.8 },
    { title: "斩魔大圣Demonbane", score: 7.4 },
    { title: "CANNONBALL：猫猫疯狂大赛车", score: 7.9 },
    { title: "没有天使的12月", score: 7.2 },
    { title: "V.G.NEO", score: 7.6 },
    { title: "めぐり、ひとひら。", score: 7.5 },
    { title: "雪歌", score: 7.1 },
  ],
  "2004": [
    { title: "神树之馆", score: 7.7 },
    { title: "交响乐之雨", score: 8.5 },
    { title: "CLANNAD", score: 8.9 },
    { title: "Fate/stay night", score: 8.3 },
    { title: "Forest", score: 8.6 },
    { title: "狂欢节", score: 7.5 },
    { title: "Remember11：无限轮回的时光", score: 8.9 },
    { title: "家族计划~再开~", score: 8.7 },
    { title: "兰斯6 - 赛斯崩坏 -", score: 7.5 },
    { title: "星之梦", score: 8 },
    { title: "春天的足音", score: 7.7 },
    { title: "寒蝉鸣泣之时", score: 8.2 },
    { title: "秋之回忆：从今以后", score: 7.7 },
    { title: "乐园～一如既往的我。的存在～", score: 8.1 },
    { title: "腐姬 归省～jamais vu～", score: 7.4 },
    { title: "初音岛 P.C.", score: 6.8 },
    { title: "四重奏！", score: 7.4 },
    { title: "那一天，去往何方", score: 7 },
    { title: "MinDeaD BlooD：献给支配者的狂死曲", score: 7.6 },
  ],
  "2005": [
    { title: "车轮之国、向日葵的少女", score: 8.1 },
    { title: "天鹅之歌", score: 8.1 },
    { title: "最后的现在", score: 8.7 },
    { title: "水仙", score: 8.5 },
    { title: "女仆咖啡帕露菲", score: 8 },
    { title: "梦见之药", score: 7.4 },
    { title: "ToHeart2 XRATED", score: 7.6 },
    { title: "我不是天使", score: 7.2 },
    { title: "皋月物语", score: 8.4 },
    { title: "夜明前的琉璃色", score: 6.8 },
    { title: "寒蝉鸣泣之时解 皆杀篇", score: 7.5 },
    { title: "娇蛮之吻", score: 7.2 },
    { title: "Fate/hollow ataraxia", score: 7.8 },
    { title: "梦幻廻廊", score: 7 },
    { title: "ジオグラマトン -Dyogrammaton-", score: 6.3 },
  ],
  "2006": [
    { title: "Muv-Luv Alternative", score: 8.8 },
    { title: "青空下的约定", score: 7.8 },
    { title: "悠久之翼-前篇", score: 7.6 },
    { title: "I/O", score: 8.1 },
    { title: "战国兰斯", score: 8.3 },
    { title: "遥仰凰华", score: 7.5 },
    { title: "寒蝉鸣泣之时解", score: 8.4 },
    { title: "离开的人们", score: 7.5 },
    { title: "雪影", score: 7.5 },
    { title: "Gore Screaming Show", score: 7 },
    { title: "她们的流仪", score: 7.1 },
    { title: "四叶草", score: 6.9 },
    { title: "EXTRAVAGANZA ～蟲愛でる少女～", score: 7.6 },
    { title: "H2O ～FOOTPRINTS IN THE SAND～", score: 7 },
  ],
  "2007": [
    { title: "KIRA☆KIRA 煌煌舞台", score: 8.5 },
    { title: "爱丽丝大游行～两位爱丽丝与不可思议的少女们", score: 6.7 },
    { title: "海猫鸣泣之时", score: 8.4 },
    { title: "水仙2", score: 8.2 },
    { title: "Little Busters!", score: 8.3 },
    { title: "片羽", score: 7.5 },
    { title: "赫炎的印加诺克 ～何等美好的人们～", score: 7.5 },
    { title: "车轮之国、悠久的少年少女", score: 7.7 },
    { title: "续·杀戮之姜戈—地狱通缉犯—", score: 8.2 },
    { title: "世界上最NG的恋爱", score: 7.5 },
    { title: "终有一日愿遂彼空", score: 7.1 },
    { title: "电塔未明", score: 7.2 },
    { title: "明日的世界", score: 7 },
    { title: "Aster", score: 7.2 },
    { title: "ITAZULOVE 在没有人烟的公园和少女孕育爱情", score: 5.7 },
  ],
  "2008": [
    { title: "428 ～被封锁的涩谷～", score: 8.5 },
    { title: "壳之少女", score: 7.6 },
    { title: "G弦上的魔王", score: 7.9 },
    { title: "Little Busters! EX", score: 8.5 },
    { title: "夏空彼方", score: 7.3 },
    { title: "缘之空", score: 7 },
    { title: "媚肉之香", score: 7.9 },
    { title: "智以泪聚", score: 7.5 },
    { title: "悠久之翼-后篇", score: 8.4 },
    { title: "11eyes -罪与罚与赎的少女-", score: 7.2 },
    { title: "MYTH", score: 7.7 },
    { title: "游魂-Kiss on my Deity-", score: 6.7 },
    { title: "FORTUNE ARTERIAL", score: 7.1 },
    { title: "漆黑的夏尔诺斯 ～何等美好的明日～", score: 7.4 },
    { title: "霞外笼逗留记", score: 8.2 },
    { title: "雨の日と雨の日の次の日", score: 0 },
    { title: "战女神ZERO", score: 8.2 },
    { title: "彼女×彼女×彼女～三姉妹とのドキドキ共同生活～", score: 6.9 },
    { title: "混沌头", score: 7 },
  ],
  "2009": [
    { title: "装甲恶鬼村正", score: 8.6 },
    { title: "BALDR SKY Dive2 ", score: 8.8 },
    { title: "星空的记忆 -Wish upon a shooting star", score: 7.8 },
    { title: "eden* They were only two, on the planet.", score: 7.9 },
    { title: "BALDR SKY Dive1 ", score: 8.5 },
    { title: "我们没有翅膀", score: 8.4 },
    { title: "海猫鸣泣之时散", score: 8.6 },
    { title: "从晴朗的朝色泛起之际开始", score: 7.6 },
    { title: "极限脱出 9小时9人9扇门", score: 8 },
    { title: "夏之雨", score: 6.9 },
    { title: "天神乱漫 -LUCKY or UNLUCKY!?-", score: 6.8 },
    { title: "鬼歌。", score: 6.1 },
    { title: "夏梦渚", score: 7.4 },
    { title: "白光的伐鲁希亚 ～何等美好的希望～", score: 7.2 },
    { title: "兰斯02~反叛的少女们~", score: 5.9 },
    { title: "纯白交响曲", score: 7.2 },
    { title: "认真和我恋爱", score: 7.9 },
    { title: "痕 ～きずあと～", score: 7.1 },
    { title: "Flyable Heart", score: 7 },
    { title: "白雪～七凭之祭～", score: 6 },
    { title: "幼驯染是大总统", score: 6.3 },
    { title: "eden* PLUS+MOSAIC", score: 7.4 },
    { title: "黑暗之蓝", score: 5.4 },
    { title: "圣诞之吻", score: 7.9 },
  ],
  "2010": [
    { title: "美好的每一天 ～不连续的存在～", score: 8.8 },
    { title: "弹丸论破 希望的学园和绝望高中生", score: 7.9 },
    { title: "海猫鸣泣之时~魔女与推理的轮舞曲~", score: 8.7 },
    { title: "黄昏的禁忌之药", score: 7.5 },
    { title: "白色相簿2 序章", score: 8.2 },
    { title: "恋爱和选举和巧克力", score: 6.6 },
    { title: "星空的记忆 永恒之心", score: 7.6 },
    { title: "白色相簿：编缀的冬日回忆", score: 7.3 },
    { title: "紫影的索纳尼尔 ～何等美好的记忆～", score: 7.8 },
    { title: "恋色空模样", score: 6.9 },
    { title: "库特wafter", score: 7 },
    { title: "Noble Works", score: 6.6 },
    { title: "混沌之脑 LOVE ChuChu", score: 6.5 },
    { title: "逆转爱恋", score: 6.4 },
    { title: "天使的星期日", score: 7.4 },
    { title: "信天翁航海录", score: 7.6 },
    { title: "光轮之町、薰衣草的少女", score: 5.3 },
    { title: "雾谷伯爵家的六姐妹", score: 6.9 },
  ],
  "2011": [
    { title: "白色相簿2 终章", score: 9 },
    { title: "秽翼的尤斯蒂娅", score: 8.3 },
    { title: "Rewrite", score: 8.6 },
    { title: "五彩斑斓的世界", score: 7.5 },
    { title: "euphoria", score: 7.2 },
    { title: "海猫鸣泣之时散～真实与幻想的夜想曲～", score: 8.7 },
    { title: "灰色的果实", score: 7.8 },
    { title: "我的女友是蓝领／她的作为，我的遭遇／巨乳妻完全捕获计划／我老婆被那家伙睡了。", score: 7.5 },
    { title: "兰斯8", score: 7.4 },
    { title: "美少女万华镜 -被诅咒的传说少女-", score: 6.9 },
    { title: "情侣热恋中", score: 7.5 },
    { title: "突然之间发现我已恋上你", score: 6.4 },
    { title: "鬼哭街 泪尽铃音响", score: 7.3 },
    { title: "不要践踏天使的羽毛", score: 7 },
    { title: "NOeSIS-虚伪记忆的物语-", score: 7.4 },
    { title: "触祭之都", score: 4.4 },
    { title: "へんし～ん!!!～パンツになってクンクンペロペロ～ パン・ツー・パック！", score: 7.3 },
    { title: "らぶ2Quad", score: 6.6 },
    { title: "Strawberry Nauts -ストロベリーノーツ-", score: 6.9 },
    { title: "妹调教日记", score: 4.9 },
    { title: "绝对高潮☆性器大发明!!―捕获学园处女的多样工口道具―", score: 6.5 },
    { title: "狗哭", score: 5.8 },
    { title: "LOVELY×CATION", score: 6.7 },
    { title: "Ever17 重制版", score: 8.5 },
  ],
  "2012": [
    { title: "魔法使之夜", score: 8.6 },
    { title: "超级弹丸论破2 再见了绝望学园", score: 8.5 },
    { title: "近月少女的礼仪", score: 7.7 },
    { title: "初雪樱", score: 7.6 },
    { title: "海市蜃楼之馆", score: 8.4 },
    { title: "五彩斑斓的曙光", score: 7.8 },
    { title: "白色相簿2 幸福的彼端", score: 8.9 },
    { title: "DRACU-RIOT!", score: 7 },
    { title: "夏空的英仙座", score: 6.3 },
    { title: "美少女万华镜 -勿忘草与永远的少女-", score: 6.8 },
    { title: "神怒之日：为爱痴狂", score: 8.4 },
    { title: "Root Double -Before Crime  After Days-", score: 7.8 },
    { title: "おたマ！～おたく仲間はちっこいマニア～", score: 6 },
    { title: "初音岛3", score: 7.2 },
    { title: "灰色的迷宫", score: 7.7 },
    { title: "在这苍穹展翅", score: 7.4 },
    { title: "幻灵镇魂曲", score: 8.2 },
    { title: "春开，意遥遥。", score: 7.5 },
    { title: "古色迷宫轮舞曲 ～HISTOIRE DE DESTIN～", score: 7.2 },
    { title: "时钟机关的Ley-line-黄昏时刻的境界线-", score: 6.7 },
    { title: "现在就想告诉哥哥，我是妹妹！", score: 6.9 },
    { title: "少女编织爱的画布", score: 6.9 },
    { title: "Remember 最爱的妻子在其他男人怀中微笑●另一种可能", score: 7.1 },
    { title: "世界终结与生日快乐", score: 7.6 },
  ],
  "2013": [
    { title: "フレラバ ～Friend to Lover～", score: 7.8 },
    { title: "大图书馆的牧羊人", score: 7.4 },
    { title: "少女理论及其周边 -巴黎学院篇-", score: 8 },
    { title: "向日葵的教会与长长的暑假", score: 7.7 },
    { title: "忠臣藏46＋1", score: 8.2 },
    { title: "你和她和她的恋爱。", score: 7.4 },
    { title: "兰斯01 寻找小光", score: 7 },
    { title: "虚之少女", score: 7.4 },
    { title: "LOVESICK PUPPIES -我们为了恋爱而诞生-", score: 7 },
    { title: "幸福噩梦", score: 7 },
    { title: "灰色的乐园", score: 7.8 },
    { title: "献给精灵神的祭品巫女供牺姬菲娜的冒险之旅", score: 7.8 },
    { title: "时钟机关的Ley-line-残影之夜将明时-", score: 7.8 },
    { title: "sisters ～夏天最后一日～ Ultra Edition", score: 7.1 },
    { title: "麻吕的患者是蓝领", score: 6.8 },
    { title: "因为妹妹太受欢迎了糟糕了。", score: 6.5 },
    { title: "復讐の死霊魔術師 ～望むのは死の痛み～", score: 6.5 },
    { title: "魔导巧壳", score: 7.4 },
    { title: "魔卡魅恋！", score: 6.8 },
    { title: "幻创的幻人 ～Oratorio Phantasm Historia～", score: 7.3 },
    { title: "我成为天使的理由", score: 7.1 },
    { title: "潜伏之赤途", score: 8.7 },
    { title: "お嬢様はご機嫌ナナメ", score: 7.3 },
    { title: "命运石之门 线形拘束的树状图", score: 7.2 },
  ],
  "2014": [
    { title: "苍之彼方的四重奏", score: 7.9 },
    { title: "混沌子", score: 8.4 },
    { title: "纸上魔法使", score: 7.9 },
    { title: "近月少女的礼仪2", score: 6.8 },
    { title: "幸运草的约定", score: 7.2 },
    { title: "西历2236年", score: 8.4 },
    { title: "若能与你再次相见", score: 7.3 },
    { title: "南十字星恋歌", score: 6.2 },
    { title: "星辰恋曲的白色永恒", score: 7.2 },
    { title: "慕情之心今随君作伴", score: 7.2 },
    { title: "冲破万里晴空之上", score: 8 },
    { title: "星織ユメミライ", score: 7.5 },
    { title: "セミラミスの天秤", score: 7 },
    { title: "甜蜜女友", score: 7.3 },
    { title: "七色轮回", score: 7.5 },
    { title: "PRIMAL×HEARTS", score: 6.9 },
    { title: "魔女恋爱日记", score: 7.3 },
    { title: "爱丽娅的明日盛典！", score: 6.1 },
    { title: "彼女が俺にくれたもの。俺が彼女にあげるもの。 ～KISS My Darling：めちゃ婚case3～", score: 6.7 },
    { title: "命运线上的Φ", score: 6.6 },
    { title: "白色相簿2 mini After Story", score: 7.5 },
    { title: "兰斯9 赫尔曼革命", score: 8.2 },
    { title: "变身！～变成那个女孩子为所欲为～", score: 7.3 },
    { title: "大图书馆的牧羊人 -Dreaming Sheep-", score: 7.1 },
  ],
  "2015": [
    { title: "樱之诗 - 在樱花之森上飞舞", score: 8.8 },
    { title: "人狼村之谜", score: 8.2 },
    { title: "魔女的夜宴", score: 7.2 },
    { title: "命运石之门 0", score: 7.9 },
    { title: "兰斯03 利萨斯陷落", score: 8.2 },
    { title: "想要传达给你的爱恋", score: 7.2 },
    { title: "永不落幕的前奏诗", score: 7.2 },
    { title: "与你心相连", score: 7.5 },
    { title: "夏娃年代记", score: 7.5 },
    { title: "妹的圣域", score: 6.2 },
    { title: "甜蜜女友～Second Season～", score: 7.3 },
    { title: "抬头看看吧，看那天上的繁星", score: 7.4 },
    { title: "时钟机关的Ley-line-朝雾中飘零之花-", score: 7.9 },
    { title: "海市蜃楼之馆 -A Requiem for Innocence-", score: 8.5 },
    { title: "美少女万华镜 -为神所创的少女们-", score: 7.2 },
    { title: "すみれ", score: 7.7 },
    { title: "花咲workspring！", score: 6.9 },
    { title: "妖蛆之饵", score: 6.7 },
    { title: "童话安魂曲", score: 7 },
    { title: "ボクはともだち。I am not sweetheart.", score: 7.2 },
    { title: "柯罗的怀表", score: 6.7 },
    { title: "正负战争", score: 6.8 },
    { title: "选择妻子的进展似乎顺利过头。", score: 6.5 },
    { title: "传颂之物-虚伪的假面-", score: 8 },
  ],
  "2016": [
    { title: "天津罪", score: 7.6 },
    { title: "千恋＊万花", score: 6.9 },
    { title: "King Exit", score: 8 },
    { title: "花之天使的夏日恋歌", score: 7.2 },
    { title: "逝去的你、于馆中萌生的憎恶", score: 6.3 },
    { title: "夏色心跳日志", score: 6.8 },
    { title: "野良与皇女与流浪猫之心", score: 7.2 },
    { title: "VA-11 HALL-A：赛博朋克酒保行动", score: 8.1 },
    { title: "来自昏暗的时间尽头", score: 7.4 },
    { title: "夏之锁", score: 6.7 },
    { title: "爱上火车", score: 6.8 },
    { title: "Re:LieF 〜献给亲爱的你〜", score: 6.9 },
    { title: "千之刃涛、桃花染之皇姬", score: 6.8 },
    { title: "银色遥远", score: 7.2 },
    { title: "少女＊领域", score: 6.7 },
    { title: "永不枯萎的世界与终结之花", score: 6.7 },
    { title: "ISLAND", score: 7.8 },
    { title: "冻京NECRO", score: 6.9 },
    { title: "游魂2 -you're the only one-", score: 6.5 },
    { title: "ラムネーション！", score: 6.9 },
    { title: "Rewrite+", score: 8.4 },
    { title: "罪之光约会", score: 6.1 },
    { title: "少女理论及其之后的周边 -美好年代篇-", score: 7.3 },
    { title: "少女マイノリティ -慰めの愛-", score: 6.2 },
  ],
  "2017": [
    { title: "流景之海的艾佩理雅", score: 8 },
    { title: "青鸟", score: 7.4 },
    { title: "金辉恋曲四重奏", score: 7.6 },
    { title: "9-nine-九次九日九重色", score: 6.4 },
    { title: "BLACKSOULS -黒の童話と五魔姫-", score: 7.4 },
    { title: "水葬银货的伊斯特利亚", score: 7.3 },
    { title: "突然＊恋人", score: 7.5 },
    { title: "まほ×ろば -Witches spiritual home-", score: 6.6 },
    { title: "天结城堡大师", score: 7.5 },
    { title: "新弹丸论破V3 大家的自相残杀新学期", score: 7.2 },
    { title: "苍之彼方的四重奏 EXTRA1", score: 7.2 },
    { title: "美少女万华镜 -罪与罚的少女-", score: 6.9 },
    { title: "月影魅像-解放之羽-", score: 7 },
    { title: "7days—与你共度的七日间", score: 7.3 },
    { title: "星辰恋曲的白色永恒 白色星之梦", score: 7.1 },
    { title: "真情流露于五彩之时", score: 7.5 },
    { title: "樱之杜†净梦者2", score: 7 },
    { title: "心跳文学部！", score: 6.8 },
    { title: "三色△绘恋", score: 5.8 },
    { title: "幕末 尽忠报国烈士传 -MIBURO-", score: 7.4 },
    { title: "樱花裁决", score: 7.3 },
    { title: "恋之巢", score: 7 },
    { title: "回家前都算是棉花糖", score: 6.5 },
    { title: "特里诺兰", score: 6.5 },
  ],
  "2018": [
    { title: "抜きゲーみたいな島に住んでる貧乳はどうすりゃいいですか？", score: 7.5 },
    { title: "Summer Pockets", score: 8.3 },
    { title: "兰斯10 决战", score: 9.3 },
    { title: "BLACKSOULSII -愛しき貴方へ贈る不思議の国-", score: 8.8 },
    { title: "9-nine-天色天歌天籁音", score: 7.2 },
    { title: "美好的每一天 ～不连续的存在～全语音HD版", score: 9 },
    { title: "少女与我、两纪之差", score: 6.7 },
    { title: "乌有乡", score: 7.3 },
    { title: "RIDDLE JOKER", score: 6.6 },
    { title: "寄宿之恋", score: 6.8 },
    { title: "奇异恩典·圣夜的小镇", score: 7.5 },
    { title: "丑小鸭与文字祸", score: 6.3 },
    { title: "5分钟的邂逅！时间停止与不可避免的命运！", score: 6.5 },
    { title: "神待少女纱波", score: 6.6 },
    { title: "如月真绫的诱惑", score: 6.5 },
    { title: "相恋之心与魔法之语", score: 6.3 },
    { title: "告别回忆 -无垢少女-", score: 7.2 },
    { title: "VenusBlood:Lagoon", score: 8 },
    { title: "未来广播与人工鸽", score: 6.6 },
    { title: "重返蓝鲸岛", score: 6.9 },
    { title: "Deep One -ディープワン-", score: 5.5 },
    { title: "末世孤雄 Vol 2", score: 6.9 },
    { title: "封缄之都古拉塞斯塔", score: 7 },
    { title: "哥哥，早上起床之前都要抱紧我哦！", score: 6.4 },
  ],
  "2019": [
    { title: "樱花、萌放。-as the Night's, Reincarnation-", score: 8.3 },
    { title: "抜きゲーみたいな島に住んでる貧乳はどうすりゃいいですか？2", score: 8.1 },
    { title: "MUSICUS!", score: 8.5 },
    { title: "9-nine-春色春恋春熙风", score: 6.9 },
    { title: "青空下的加缪", score: 7.1 },
    { title: "星光咖啡馆与死神之蝶", score: 6.4 },
    { title: "金辉恋曲四重奏 -Golden Time-", score: 7.5 },
    { title: "恋愛、借りちゃいました", score: 6.8 },
    { title: "异想魅惑", score: 7.2 },
    { title: "在月之彼岸邂逅", score: 7.4 },
    { title: "VenusBlood FRONTIER International", score: 7.6 },
    { title: "pieces/候鸟的梦", score: 7 },
    { title: "玉响未来", score: 7 },
    { title: "母烂漫", score: 7.4 },
    { title: "火焰之纹章 风花雪月", score: 7.6 },
    { title: "夏日狂想曲：乡间的难忘回忆", score: 7.2 },
    { title: "スタディ§ステディ", score: 6.8 },
    { title: "Christmas Tina -泡沫冬景-", score: 6.9 },
    { title: "美好国度的建设方略", score: 7.1 },
    { title: "スワローテイル -あの日、青を超えて-", score: 6.6 },
    { title: "DEAD DAYS", score: 6.3 },
    { title: "千之刃涛、桃花染之皇姬 -柳暗花明-", score: 6.4 },
    { title: "青夏轨迹", score: 7 },
    { title: "密语", score: 6.3 },
  ],
  "2020": [
    { title: "Summer Pockets REFLECTION BLUE", score: 8.4 },
    { title: "甜蜜女友2", score: 7.4 },
    { title: "樱色之云绯色之恋", score: 7.7 },
    { title: "常轨脱离Creative", score: 6.9 },
    { title: "9-nine-雪色雪花雪之痕", score: 7.7 },
    { title: "星空列车与白的旅行", score: 7.5 },
    { title: "爱上火车-Last Run!!-", score: 7.2 },
    { title: "白日梦的构想图", score: 7.5 },
    { title: "美少女万华镜 -理与迷宫的少女-", score: 7.4 },
    { title: "恋爱X决胜战", score: 6.4 },
    { title: "丸子与银河龙", score: 7.5 },
    { title: "多娜多娜 一起干坏事吧", score: 7.4 },
    { title: "保健室的老师与沉迷吹泡泡的助手", score: 7.2 },
    { title: "Saleté", score: 7.2 },
    { title: "终之空 remake", score: 7.6 },
    { title: "绽放★青春全力向前冲！", score: 6.1 },
    { title: "水莲与紫苑", score: 6.4 },
    { title: "HaremKingdom -ハーレムキングダム-", score: 6.7 },
    { title: "天之少女", score: 8.2 },
    { title: "巧克甜恋", score: 6.3 },
    { title: "徒花异谭", score: 7.3 },
    { title: "爱因斯坦携爱敬上", score: 5.8 },
    { title: "放学后的灰姑娘", score: 7.1 },
    { title: "青春フラジャイル", score: 6.3 },
  ],
  "2021": [
    { title: "永恒世界", score: 8.4 },
    { title: "9-nine- 新章", score: 6.1 },
    { title: "我们是不能延期了", score: 7.2 },
    { title: "月姬 -A piece of blue glass moon-", score: 8.2 },
    { title: "Monkeys!¡", score: 7.2 },
    { title: "圣骑士莉卡物语 白翼与淫翼姐妹", score: 7.7 },
    { title: "冬暮川滚滚", score: 7.3 },
    { title: "创作彼女的恋爱方程式", score: 6.1 },
    { title: "海沙风云", score: 7.3 },
    { title: "星之梦 -雪圈球-", score: 6.2 },
    { title: "D.C.4 Plus Harmony", score: 6.5 },
    { title: "吹弹！丰盈！波涛汹涌！异世界魅魔学园！", score: 7.2 },
    { title: "海猫鸣泣之时咲～猫箱和梦想的交响曲～", score: 8.8 },
    { title: "Demons Roots", score: 8.3 },
    { title: "纯爱咖啡厅～帕露菲重制版～", score: 7.7 },
    { title: "久那土国记", score: 6.6 },
    { title: "冥契的牧神节", score: 7.6 },
    { title: "我与公主骑士及侍女的慢活生活", score: 6.1 },
    { title: "同级生 重制版", score: 7 },
    { title: "ROLEPLAYER：小粥姐妹的黏膜游戏！", score: 7.1 },
    { title: "我的恋天使太废柴了好可怕", score: 6.1 },
    { title: "PARQUET", score: 5.7 },
  ],
  "2022": [
    { title: "变态监狱", score: 8.7 },
    { title: "炽焰天穹", score: 7.2 },
    { title: "废村少女 ～妖异魅惑的笼之乡～", score: 6.8 },
    { title: "苍之彼方的四重奏 EXTRA2", score: 8.3 },
    { title: "星之终途", score: 7.5 },
    { title: "ハミダシクリエイティブ凸", score: 6.8 },
    { title: "BLACK SHEEP TOWN", score: 8.4 },
    { title: "甜蜜夏日", score: 7 },
    { title: "恋爱成双", score: 6.7 },
    { title: "妹！相随 ~黑白世界的缤纷冒险~", score: 7.5 },
    { title: "ジュエリー・ハーツ・アカデミア -We will wing wonder world-", score: 7.3 },
    { title: "魔法使之夜", score: 9.2 },
    { title: "为主人献上圣罗的甜蜜侍奉", score: 6.4 },
    { title: "主播女孩重度依赖", score: 7 },
    { title: "与鲨鱼共度的七日间", score: 7 },
    { title: "无法忍耐的处男哥哥和不直率的叛逆妹妹", score: 6.9 },
    { title: "アンレス・テルミナリア", score: 5.9 },
    { title: "D.C.4 Sweet Harmony ～ダ・カーポ4～ スイートハーモニー", score: 7 },
    { title: "Dreamin' Her -我梦见了她。-", score: 6.9 },
    { title: "スタディ§ステディ2", score: 6.9 },
    { title: "もっと！孕ませ！炎のおっぱい異世界おっぱいメイド学園！", score: 7.4 },
    { title: "ROLEPLAYER：山掛姐妹的黏膜游戏！", score: 6.2 },
    { title: "FLIP＊FLOP 〜INNOCENCE OVERCLOCK〜", score: 6 },
    { title: "妹妹母亲～母性萝莉", score: 5.8 },
  ],
  "2023": [
    { title: "甜蜜女友2+", score: 8 },
    { title: "樱之刻 - 于樱花之森下漫步", score: 8.3 },
    { title: "纯白交响曲 SANA EDITION", score: 7.6 },
    { title: "恋狱～月狂病～ 重制版", score: 7.9 },
    { title: "Hira Hira Hihiru", score: 7.8 },
    { title: "天使☆嚣嚣 RE-BOOT!", score: 6 },
    { title: "纯白交响曲 Remake for FHD", score: 7.2 },
    { title: "GINKA", score: 5.9 },
    { title: "D.C.5 ～ダ・カーポ5～", score: 7.2 },
    { title: "繁花落舞恋如樱-Re:BIRTH-", score: 6.6 },
    { title: "こあくまちゃんの誘惑っ！", score: 5.9 },
    { title: "密语-Silver Snow Sister-", score: 6.5 },
    { title: "妖夢員:The Nightmaretaker ～悪魔に憑かれた男～", score: 7.1 },
    { title: "Geminism", score: 6.2 },
    { title: "FLIP＊FLOP 〜RAMBLING OVERRUN〜", score: 5.9 },
    { title: "如神之馆～欲望的247～", score: 6.9 },
    { title: "火山的女儿", score: 7.1 },
    { title: "巧克甜恋3", score: 7 },
    { title: "八卦恋爱", score: 6.6 },
    { title: "放課後シンデレラ２ ミニファンディスク ～君と踊る初めてのハッピーハロウィン～", score: 6.8 },
    { title: "TO･RA･WA･SE ～囚われの偽妃が夢みる初夜～", score: 6.8 },
    { title: "我的眼睛能看光光！不可知的未来与透视的命运", score: 5.7 },
    { title: "犹格索托斯的庭院", score: 6.7 },
  ],
  "2024": [
    { title: "播种之谣", score: 7.7 },
    { title: "秘密之恋（伪）", score: 6 },
    { title: "饿殍：明末千里行", score: 6.3 },
    { title: "美少女万华镜异闻 雪女", score: 6.2 },
    { title: "D.C.5 Plus Happiness ～ダ・カーポ5～プラスハピネス", score: 7.6 },
    { title: "异想魅惑2暮色廻奇谭", score: 6.5 },
    { title: "ラブピカルポッピー！", score: 6.7 },
    { title: "旭光のマリアージュ", score: 6.8 },
    { title: "米塔", score: 7.2 },
    { title: "悠刻のファムファタル", score: 6.8 },
    { title: "Fate/stay night REMASTERED", score: 7.6 },
    { title: "催眠性指导 -秘密课程-", score: 6.5 },
    { title: "双天†恋姬～至源的王～", score: 6.8 },
    { title: "梦幻的提尔纳诺", score: 5.4 },
    { title: "月乡幽灵", score: 6.4 },
    { title: "启动世界的理想论 -goodbye world index-", score: 6.9 },
    { title: "甜蜜夏日+", score: 6.9 },
    { title: "不/存在的你，和我", score: 5.6 },
    { title: "贽之匣庭", score: 5.5 },
    { title: "我的姐姐被恶霸强奸", score: 5.6 },
    { title: "天选庶民的真命之选", score: 5.3 },
    { title: "宝石少女 1st.cut:The Reason She Must Perish", score: 6.8 },
    { title: "濒死的骑士、于异世界中响彻的绝唱", score: 6 },
    { title: "夏色四叶草", score: 7.1 },
  ],
};

export default data;
