type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2000": [
    { title: "月姬", score: 8.2 },
    { title: "永恒格斗零", score: 7.6 },
    { title: "2nd LOVE", score: 6.8 },
    { title: "既知街 2 大虐殺", score: 0 },
    { title: "Summer Solstice ～夏死～", score: 0 },
    { title: "书淫，或是已失去的梦之物语。", score: 7.2 },
    { title: "8月7日の雨宿り", score: 0 },
    { title: "かえで通り —brandnew days innocent—", score: 0 },
    { title: "Duette II ～デュエット2～", score: 0 },
    { title: "Stay. -Fragments of Memories-", score: 0 },
    { title: "リーベ ～想い出の贈り物～", score: 0 },
    { title: "MoonLight ～おもいでのはじまり～", score: 0 },
    { title: "夕顔", score: 0 },
    { title: "隠れ月", score: 0 },
    { title: "Close 2U ～最後の夏休み～", score: 0 },
    { title: "Started Dirge", score: 0 },
    { title: "MaYa ～微睡島の眠姫～", score: 0 },
    { title: "Photogenic", score: 0 },
    { title: "BF", score: 0 },
  ],
  "2001": [
    { title: "歌月十夜", score: 7.5 },
    { title: "月姬 PLUS-DISC", score: 6.6 },
    { title: "ひとかた", score: 0 },
    { title: "1999ChristmasEve", score: 0 },
    { title: "masher", score: 0 },
    { title: "夏桜", score: 0 },
    { title: "泡沫 ~うたかた~", score: 0 },
    { title: "おジャ魔女どれみ しゅーとっ", score: 0 },
    { title: "Pray to Snow", score: 0 },
    { title: "birdie～ぼくらの恋愛心理学～", score: 0 },
    { title: "Wing＆Wind", score: 0 },
    { title: "苍黑之月", score: 0 },
    { title: "One Way Love ～ミントちゃん物語～", score: 0 },
    { title: "Bisquieholic Eqations", score: 0 },
    { title: "ＯＮＦ～闘う羅刹へ～", score: 0 },
    { title: "YAMANNAD", score: 0 },
    { title: "Foster", score: 0 },
    { title: "雪明りのMelody", score: 0 },
    { title: "うにゅうにゅ", score: 0 },
    { title: "The Executioner", score: 0 },
    { title: "ライジングビート", score: 0 },
    { title: "スキャンダラスラプソディ", score: 0 },
    { title: "ミラクルハート", score: 0 },
    { title: "STARDUST BLUE", score: 0 },
  ],
  "2002": [
    { title: "东方红魔乡 ～ the Embodiment of Scarlet Devil.", score: 7.9 },
    { title: "睡莲", score: 7.2 },
    { title: "月姬格斗", score: 7.3 },
    { title: "星合いの空", score: 0 },
    { title: "あの､素晴らしい　をもう一度", score: 0 },
    { title: "寒蝉鸣泣之时 绵流篇", score: 8.1 },
    { title: "I’m ～心の向こう側に～", score: 0 },
    { title: "透幻鏡", score: 0 },
    { title: "Romancing Kanon ～永遠の少女伝説～", score: 0 },
    { title: "寒蝉鸣泣之时 鬼隐篇", score: 7.6 },
    { title: "夢の終わり", score: 0 },
    { title: "紅いシャーレ", score: 0 },
    { title: "霞我身", score: 0 },
    { title: "夏日共鸣", score: 0 },
    { title: "Stitch -掛け違えたボタン-", score: 0 },
    { title: "bois ～機械じかけの街～", score: 0 },
    { title: "Kinoko2", score: 0 },
    { title: "月のあかり猫のひとみ", score: 0 },
    { title: "カフェ・リンドバーグ～ぼくらの恋愛心理学2～", score: 0 },
    { title: "闇色の器", score: 0 },
    { title: "Piece of Wonder", score: 0 },
    { title: "想い出よりせつなく", score: 0 },
    { title: "ボクの彼氏はジュリエット", score: 0 },
    { title: "蒼黒の月外伝～幻夜の書～", score: 0 },
  ],
  "2003": [
    { title: "TRUE REMEMBRANCE", score: 7.1 },
    { title: "终末之际", score: 6 },
    { title: "Petit Fleur～拂过小镇的旋律之风～", score: 6.7 },
    { title: "东方妖妖梦 ～ Perfect Cherry Blossom.", score: 8.1 },
    { title: "花归葬", score: 7.9 },
    { title: "圣火的纹章", score: 6.2 },
    { title: "悠遠ノ絲", score: 0 },
    { title: "冬は幻の鏡", score: 0 },
    { title: "牧岛侦探事务所物语 ～深宅中的怨恨 ～", score: 6.4 },
    { title: "寒蝉鸣泣之时 祟杀篇", score: 7.9 },
    { title: "Moon Shade", score: 0 },
    { title: "Erinyes", score: 0 },
    { title: "二十四季", score: 0 },
    { title: "NoAREA", score: 0 },
    { title: "潮風の街", score: 0 },
    { title: "MARIONETTE～糸使い～", score: 6.8 },
    { title: "カゲ、フマズ", score: 0 },
    { title: "かたおもい", score: 0 },
    { title: "クリアファイル 少女と唄と幽霊屋敷", score: 0 },
    { title: "紅く輝く雪", score: 0 },
    { title: "東京貴族", score: 0 },
    { title: "My Sweet Home", score: 0 },
    { title: "風と光があなたに恵みますように", score: 0 },
    { title: "- no reason -", score: 0 },
  ],
  "2004": [
    { title: "东方永夜抄 ～ Imperishable Night.", score: 8.3 },
    { title: "寒蝉鸣泣之时", score: 8.2 },
    { title: "想瞬谱", score: 7.1 },
    { title: "东方萃梦想 ～ Immaterial and Missing Power.", score: 7.5 },
    { title: "梦日记", score: 7.8 },
    { title: "青鸟的虚像", score: 7.9 },
    { title: "It's so flogging molly", score: 5.4 },
    { title: "Endless Rain", score: 7.4 },
    { title: "夏之灯火", score: 6.9 },
    { title: "ロストカラーズ", score: 0 },
    { title: "寒蝉鸣泣之时解 目明篇", score: 8.2 },
    { title: "兎の輪舞", score: 0 },
    { title: "永远的夏日", score: 0 },
    { title: "インクルージョン", score: 0 },
    { title: "三枪手悖论", score: 4.9 },
    { title: "仙境传说：格斗版", score: 7.3 },
    { title: "月光のアドニス", score: 5.9 },
    { title: "puncTure", score: 4.8 },
    { title: "Purism×Egoist", score: 0 },
    { title: "Seraphic Blue", score: 8.7 },
    { title: "です☆めた ～半熟ヴァンパイア死亡YOU戯～", score: 0 },
    { title: "Qualia～クオリア～", score: 0 },
    { title: "NETANNAD", score: 0 },
    { title: "NooN -いつもより少しだけ長かったあの夏の一日-", score: 0 },
  ],
  "2005": [
    { title: "忘却之物与遗落之物", score: 7 },
    { title: "东方花映塚 ～ Phantasmagoria of Flower View.", score: 7.6 },
    { title: "水仙", score: 8.5 },
    { title: "灯穗奇谭", score: 6.9 },
    { title: "乐园-Eden", score: 6.1 },
    { title: "紧缚王子", score: 6.5 },
    { title: "东方文花帖 ～ Shoot the Bullet.", score: 7.5 },
    { title: "阳光下的真实", score: 6.7 },
    { title: "Bad Name", score: 6.8 },
    { title: "天に高く地に深く", score: 7.4 },
    { title: "盛夏之梦  A Dream of Summer", score: 6.6 },
    { title: "蔷薇少女同人格斗", score: 6.9 },
    { title: "寒蝉鸣泣之时解 罪灭篇", score: 7.9 },
    { title: "Diorama -ジオラマ-", score: 0 },
    { title: "哆啦A梦：野比大雄的生化危机", score: 6.7 },
    { title: "空とキオクの彼方", score: 0 },
    { title: "空の上のおもちゃ", score: 7.5 },
    { title: "君が見せた笑顔", score: 0 },
    { title: "SEED同人作品", score: 0 },
    { title: "CLANN -クラン-", score: 0 },
    { title: "さくっとパンダ 〜苦痛〜", score: 6 },
    { title: "火焰之纹章：圣邪的意志", score: 8 },
    { title: "セトの海から", score: 0 },
    { title: "はーみっと こんぷれっくす", score: 0 },
  ],
  "2006": [
    { title: "寒蝉鸣泣之时解", score: 8.4 },
    { title: "离开的人们", score: 7.5 },
    { title: "黑曜镜的魔兽", score: 7.3 },
    { title: "料理", score: 4.7 },
    { title: "B.B.ライダー", score: 8.5 },
    { title: "キラークイーン", score: 7.1 },
    { title: "凉宫春日的逆转", score: 6.3 },
    { title: "寒蝉鸣泣之时礼", score: 7.5 },
    { title: "东方梦终剧", score: 7.5 },
    { title: "終ノ刻印", score: 0 },
    { title: "夜蝶綺譚", score: 0 },
    { title: "露赛提娅～道具屋经营妙方～", score: 7.4 },
    { title: "破瓜病-クワビヤウ-", score: 0 },
    { title: "男土下座地獄", score: 5 },
    { title: "Aguni ～運命の先～", score: 6.1 },
    { title: "さくっとパンダ～妄想交響曲～", score: 0 },
    { title: "胡蝶の棺", score: 0 },
    { title: "ですろり 一章 ～チカラ～", score: 0 },
    { title: "育成日记", score: 6.7 },
    { title: "The noose", score: 6.3 },
    { title: "エーデルヴァイス", score: 6.8 },
    { title: "自虐の詩 Another Birthday", score: 0 },
    { title: "Ringlet", score: 0 },
    { title: "虹の彼方に", score: 0 },
  ],
  "2007": [
    { title: "电塔未明", score: 7.2 },
    { title: "40日40夜之雨", score: 6 },
    { title: "向日葵", score: 8 },
    { title: "太太是惨杀少女", score: 6.1 },
    { title: "水仙2", score: 8.2 },
    { title: "东方风神录 ～ Mountain of Faith.", score: 8.2 },
    { title: "My Sweet Home", score: 7 },
    { title: "紫陽花しようか！", score: 7.2 },
    { title: "まり∞くり -marriage crimson-", score: 5.4 },
    { title: "海猫鸣泣之时", score: 8.4 },
    { title: "少年の国の少女アリス", score: 4.9 },
    { title: "萝莉的时间", score: 5.6 },
    { title: "猫猫马里奥", score: 6.5 },
    { title: "Zodiarc", score: 8.4 },
    { title: "悪の教科書 Textbook Of Evil", score: 6.7 },
    { title: "夏咲きのまぼろし", score: 7.8 },
    { title: "月照 ～Tsuki No Terasu～", score: 5.8 },
    { title: "死に至る病", score: 7.3 },
    { title: "梦2记", score: 8.7 },
    { title: "学校发生过的恐怖故事 ～Visual Novel Version～", score: 6.5 },
    { title: "Bye", score: 0 },
    { title: "時流", score: 0 },
    { title: "さくっとパンダ ～鬼蛇～", score: 0 },
    { title: "15歳だった―", score: 6.4 },
  ],
  "2008": [
    { title: "Ruina 废都物语", score: 8.8 },
    { title: "MYTH", score: 7.7 },
    { title: "东京爱丽丝", score: 7.1 },
    { title: "缸底", score: 5.3 },
    { title: "天命", score: 6.7 },
    { title: "东方地灵殿 ～ Subterranean Animism.", score: 7.9 },
    { title: "灵刀姬樱 ～樱花之剑与惑龙章～", score: 7.7 },
    { title: "意识流", score: 6.9 },
    { title: "刻痕", score: 6.6 },
    { title: "暗黑女王外传", score: 6.7 },
    { title: "天命～短篇集～", score: 6.5 },
    { title: "东方绯想天 ～ Scarlet Weather Rhapsody.", score: 8 },
    { title: "惧魔症候群", score: 6.5 },
    { title: "ルーデシア～Spidering with Scraping～", score: 7.5 },
    { title: "酷罪を受けるべき者", score: 7.7 },
    { title: "图书室的Neversista「THE FOOL」", score: 7.1 },
    { title: "铃音之歌、初音之声", score: 6.5 },
    { title: "梦妖尤娜的奉仕课程", score: 4.9 },
    { title: "对不起，我是个NPC", score: 7.2 },
    { title: "亲吻那片花瓣 ～爱上你的幸福～", score: 6.9 },
    { title: "幼性反应", score: 3.6 },
    { title: "致命伪装2", score: 6.8 },
    { title: "Ｎと言う名の男、Ｂと言う名の女", score: 0 },
    { title: "亲吻那片花瓣 ～珍爱的相片～", score: 6.7 },
  ],
  "2009": [
    { title: "海猫鸣泣之时散", score: 8.6 },
    { title: "东方非想天则 ～ 追寻特大型人偶之谜", score: 8.1 },
    { title: "黑色星期天", score: 7.5 },
    { title: "东方星莲船 ～ Undefined Fantastic Object.", score: 7.8 },
    { title: "薇莎露的日记", score: 8.2 },
    { title: "他与她与她的忠义", score: 6.5 },
    { title: "将所有的歌献给未来的你", score: 6.5 },
    { title: "鸑鷟：镜花水月", score: 6.4 },
    { title: "解体插入新书", score: 2.7 },
    { title: "冠を持つ神の手", score: 8.7 },
    { title: "东方幻想麻将", score: 6.7 },
    { title: "东方夜神雪", score: 7.1 },
    { title: "红魔城传说 绯色的交响曲", score: 7.1 },
    { title: "魔法少女武斗祭 完全版", score: 7.1 },
    { title: "無能宣言", score: 8.8 },
    { title: "Dear world -Re.-", score: 7.8 },
    { title: "暗黑女王本传", score: 6.9 },
    { title: "キナナキノ森", score: 7.3 },
    { title: "初音未来：注视着你瞳里的未来的歌谣", score: 6.3 },
    { title: "Battle Moon Wars 银", score: 8.2 },
    { title: "月夜响荡曲 Rebirth", score: 7.6 },
    { title: "命运召唤尔茄的精灵石", score: 7.5 },
    { title: "鴉Aの哀れな断頭台", score: 6.1 },
    { title: "刻痕Ⅲ -The Innocent LunA:Eclipsed SinnerS", score: 7.9 },
  ],
  "2010": [
    { title: "向日葵：Aqua After", score: 7.5 },
    { title: "追忆的花束献给行将灭亡的世界", score: 7.8 },
    { title: "图书室的Neversista", score: 8.2 },
    { title: "该死的妹子", score: 3.8 },
    { title: "麻衣酱的诱惑", score: 5.5 },
    { title: "风闻小镇的伯爵大人", score: 6.8 },
    { title: "图书室的Neversista 「四月的鱼～Poisson d'avril～」", score: 7.8 },
    { title: "口袋妖怪 漆黑的魅影", score: 8 },
    { title: "Cancel a format", score: 6.9 },
    { title: "红魔城传说2 妖幻的镇魂歌", score: 7.7 },
    { title: "没有黎明之夜来临之前", score: 6.1 },
    { title: "鸑鷟：橘子传", score: 5.9 },
    { title: "暗之部屋", score: 7.7 },
    { title: "战国的黑百合~扶她公主与仆从少女~", score: 6.6 },
    { title: "无限夜行", score: 7.3 },
    { title: "东方苍神缘起", score: 7.6 },
    { title: "東方口袋戰爭EVO", score: 7.4 },
    { title: "Minstrel -壊レタ人ギョウ-", score: 7.3 },
    { title: "我所希冀的未来", score: 6.6 },
    { title: "魔理沙与六色蘑菇", score: 7.3 },
    { title: "妖精大战争 ~ 东方三月精", score: 7.6 },
    { title: "徒然日记", score: 6.2 },
    { title: "Indigo", score: 0 },
    { title: "这世上最残酷的亲吻", score: 6.4 },
  ],
  "2011": [
    { title: "悲伤综合症", score: 7.6 },
    { title: "勇者大战魔物娘! 前章～输掉就会被妖女硬上～", score: 7.2 },
    { title: "朝霞之歌", score: 6.5 },
    { title: "孤独少女的百合物语", score: 6.9 },
    { title: "月界金融末世录 第一章", score: 7.2 },
    { title: "勇者大战魔物娘! 中章～输掉就会被妖女硬上～", score: 7.5 },
    { title: "囧魂", score: 7.8 },
    { title: "远去之日的花", score: 5.7 },
    { title: "演劇少女は古都鎌倉を雪で潰す", score: 7.5 },
    { title: "worst☆contact ～死神女友与外星人～", score: 7.2 },
    { title: "雾上的伊拉斯谟", score: 7.5 },
    { title: "俺たちが死んだ夏、天使のいた三日間。", score: 6.5 },
    { title: "妹调教日记", score: 4.9 },
    { title: "说谎的娜蕾特与柔情的暗杀者", score: 7.2 },
    { title: "东方神灵庙 ～ Ten Desires.", score: 7.7 },
    { title: "闇を奔る刃の煌き", score: 7.7 },
    { title: "草泥马相随", score: 5.2 },
    { title: "不泣败犬", score: 6 },
    { title: "NOeSIS-虚伪记忆的物语-", score: 7.4 },
    { title: "朽ち果てぬ桜の", score: 5.8 },
    { title: "メランコリック・ドリィムタワー", score: 0 },
    { title: "遗忘花园", score: 6.1 },
    { title: "クリアレイン", score: 7.2 },
    { title: "彼岸花盛开之夜 第一夜", score: 7.3 },
  ],
  "2012": [
    { title: "海市蜃楼之馆", score: 8.4 },
    { title: "东方年代记 双姬蓬莱物语", score: 8.5 },
    { title: "片轮少女", score: 7.3 },
    { title: "J.Q.V 人类救济部", score: 7.7 },
    { title: "幼驯染与十年之夏", score: 7.1 },
    { title: "妖妖剑戟梦想", score: 7.3 },
    { title: "箱贰伍遗体", score: 5.1 },
    { title: "恐怖美术馆", score: 7.8 },
    { title: "三国志姜维传", score: 8.5 },
    { title: "NOeSIS02-羽化-", score: 7.6 },
    { title: "とらぶるだいあり～・ごーるど", score: 6.8 },
    { title: "魔女之家", score: 7.7 },
    { title: "Nの食卓", score: 7.6 },
    { title: "月界金融末世录 第二章", score: 7.6 },
    { title: "3m -被提线木偶们玩弄的提线木偶", score: 3.9 },
    { title: "鸑鷟：摩耶之纱 女警篇", score: 5.7 },
    { title: "Color of White", score: 6.9 },
    { title: "狂父", score: 6.9 },
    { title: "古明地觉的节操教育", score: 7.3 },
    { title: "蟲ノ目・祀", score: 7.9 },
    { title: "S.I.S.T.A.R.S:KISS OF TRINITY", score: 7 },
    { title: "玫瑰与枪的日子", score: 8 },
    { title: "私は女優になりたいの", score: 6.7 },
    { title: "EDEN -最終戦争少女伝説-", score: 6.9 },
  ],
  "2013": [
    { title: "献给精灵神的祭品巫女供牺姬菲娜的冒险之旅", score: 7.8 },
    { title: "fault - milestone one", score: 7.3 },
    { title: "潜伏之赤途", score: 8.7 },
    { title: "第七境", score: 7.5 },
    { title: "勇者大战魔物娘! 终章～输掉就会被妖女硬上～", score: 7.8 },
    { title: "轨道★彩虹", score: 7.8 },
    { title: "パコられ", score: 6.4 },
    { title: "死亡直播间", score: 6.2 },
    { title: "妹调教日记√happy end & another", score: 5.6 },
    { title: "月界金融末世录 第三章", score: 7.7 },
    { title: "樱哉", score: 7.6 },
    { title: "西历2236年的秘书", score: 6.5 },
    { title: "东方辉针城 ～ Double Dealing Character.", score: 7.6 },
    { title: "Sweet Present for Shin", score: 6.6 },
    { title: "东方心绮楼 ～ Hopeless Masquerade.", score: 7.5 },
    { title: "对异形活祭神官缇娜", score: 5.3 },
    { title: "いばら姫", score: 6.1 },
    { title: "スターズ★ピース 恋愛応援⇒友達獲得ケーカク", score: 0 },
    { title: "乳牛物语", score: 7.4 },
    { title: "图书室的Neversista「∞的悲剧」", score: 8.4 },
    { title: "帽子世界", score: 7.7 },
    { title: "变身妄想", score: 4.4 },
    { title: "魔女的处刑日～上弦之月俯视着我～前篇", score: 7.6 },
    { title: "OL监禁绝顶调教", score: 4.5 },
  ],
  "2014": [
    { title: "西历2236年", score: 8.4 },
    { title: "我的超级现充生活", score: 7.6 },
    { title: "轮舞曲Duo -夜明的最强音-", score: 7.4 },
    { title: "さよなら、うつつ。", score: 7 },
    { title: "与小萝莉相思相爱", score: 6.6 },
    { title: "东方红辉心", score: 7.2 },
    { title: "口袋少女", score: 7.1 },
    { title: "第七号列车", score: 6.2 },
    { title: "高考恋爱100天", score: 6.6 },
    { title: "SummerGirl-夏之少女与我-", score: 6.2 },
    { title: "弹幕天邪鬼 ～ Impossible Spell Card.", score: 7.7 },
    { title: "TS魔法少女なお!", score: 6.9 },
    { title: "永恒的赛妮亚", score: 7 },
    { title: "PRICE", score: 6.4 },
    { title: "雨的边缘", score: 6.9 },
    { title: "東方幕華祭  ~  Fantastic Danmaku Festival", score: 7.4 },
    { title: "キリンの国", score: 7.6 },
    { title: "マジカルアイズ -Red is for anguish-", score: 0 },
    { title: "钟情一见", score: 6.4 },
    { title: "幻想人形演舞", score: 6.9 },
    { title: "デイグラシアの羅針盤", score: 0 },
    { title: "とらぶるだいあり～・ぴーち", score: 6.8 },
    { title: "巫剑神威控", score: 5.8 },
    { title: "みすずの国", score: 6.5 },
  ],
  "2015": [
    { title: "海市蜃楼之馆 -A Requiem for Innocence-", score: 8.5 },
    { title: "与奴隶的生活 -Teaching Feeling-", score: 6.3 },
    { title: "末世孤雄 Vol 1", score: 7 },
    { title: "恋生恋逝恋相随", score: 6.8 },
    { title: "Lilitales -莉莉传奇-", score: 7.1 },
    { title: "精神逻辑·爱情喜剧", score: 6.6 },
    { title: "春へと続く丘", score: 7.3 },
    { title: "勇者大战魔物娘RPG 前章", score: 7.6 },
    { title: "箱庭的学园", score: 4.7 },
    { title: "W-Standard,Wonderland Lv.1", score: 8 },
    { title: "死埋葬", score: 6.3 },
    { title: "等間隔の黒い透明", score: 7.1 },
    { title: "东方绀珠传 ～ Legacy of Lunatic Kingdom.", score: 7.9 },
    { title: "神林家殺人事件", score: 7.4 },
    { title: "告白日", score: 5.5 },
    { title: "抗战胜利70周年大阅兵这天我老婆突然消失了", score: 6 },
    { title: "fault - milestone two 上", score: 7.5 },
    { title: "Once'", score: 5.8 },
    { title: "美丽新世界~飞向阿布拉克萨斯的小鸟", score: 5.6 },
    { title: "外道勇者一行", score: 6.2 },
    { title: "ボクはともだち。I am not sweetheart.", score: 7.2 },
    { title: "Carpe Diem", score: 4.8 },
    { title: "兽耳娘奴隶", score: 6.1 },
    { title: "再见、援交妹。", score: 6.2 },
  ],
  "2016": [
    { title: "King Exit", score: 8 },
    { title: "海底", score: 8.5 },
    { title: "寝之金鸟", score: 7.1 },
    { title: "旧书店街的桥姬", score: 8.1 },
    { title: "火树银花", score: 7.3 },
    { title: "拉比哩比", score: 7.6 },
    { title: "さよなら、うつつ。 ～金で買える程度のハッピーデッドエンド追加版～", score: 7.7 },
    { title: "去人たちZERO -prologue-", score: 7 },
    { title: "小红帽之森", score: 5.5 },
    { title: "雨衣カノジョ-A面-", score: 6.9 },
    { title: "トライアンソロジー ～三面鏡の国のアリス～", score: 7.6 },
    { title: "J.Q.V人類救済部～With love from isotope～ Lost Route エデンの証明", score: 7.9 },
    { title: "十二色的季节", score: 5.9 },
    { title: "露奈的药店～提亚拉岛的药师～", score: 6.8 },
    { title: "結婚主義国家", score: 8.2 },
    { title: "装甲恶鬼村正 赎罪篇", score: 7 },
    { title: "东方夏夜祭 ～ Shining Shooting Star", score: 8 },
    { title: "古风萝莉之病娇默示录", score: 5 },
    { title: "向美好的世界献上祝福！in the life", score: 7 },
    { title: "带你下地狱病娇凶娘～love one another～", score: 3.8 },
    { title: "ちゅーそつ！1st graduation～ちゅーそつのTime after time～", score: 0 },
    { title: "Dungeon Town 遗迹之森与梦魔之药", score: 7.2 },
    { title: "真夏の朝", score: 5.4 },
    { title: "你好夏洛特 EP2: Requiem Aeternam Deo", score: 7.7 },
  ],
  "2017": [
    { title: "BLACKSOULS -黒の童話と五魔姫-", score: 7.4 },
    { title: "心跳文学部！", score: 6.9 },
    { title: "你去死吧 －多数决死亡游戏－", score: 7.8 },
    { title: "プロナント・シンフォニー", score: 7.9 },
    { title: "海市蜃楼之馆 -游魂归梦-", score: 8.6 },
    { title: "我今日将在此死去", score: 6.4 },
    { title: "カガミハラ/ジャスティス", score: 7.7 },
    { title: "芙兰与罪人之岛", score: 6.5 },
    { title: "Dear My Abyss", score: 7.5 },
    { title: "同居恋人洛丽塔", score: 6.4 },
    { title: "遊郭に売られた俺の彼女", score: 7.5 },
    { title: "妹妹旅行", score: 6.4 },
    { title: "凋零余波", score: 7.6 },
    { title: "NOeSIS03-歌う影の戯曲-", score: 6.4 },
    { title: "东方天空璋 ～ Hidden Star in Four Seasons.", score: 7 },
    { title: "东方凭依华 ～ Antinomy of Common Flowers.", score: 7.3 },
    { title: "Ewig -エーヴィヒ- 第一章「永遠＊＊」", score: 7.4 },
    { title: "雪子の国", score: 7.9 },
    { title: "关于我被小学女生绑架这件事", score: 4.3 },
    { title: "阿尔卑斯与危险森林", score: 6.6 },
    { title: "丰裕之角 －不可思议之物居住的小镇－", score: 7.9 },
    { title: "蓝宝石般的被害妄想少女", score: 7.7 },
    { title: "勇者大战魔物娘RPG 中章", score: 8.1 },
    { title: "群青之雪", score: 7.2 },
  ],
  "2018": [
    { title: "BLACKSOULSII -愛しき貴方へ贈る不思議の国-", score: 8.8 },
    { title: "1room -离家出走的少女-", score: 6.6 },
    { title: "重返蓝鲸岛", score: 6.9 },
    { title: "末世孤雄 Vol 2", score: 6.9 },
    { title: "末世孤雄 Vol 3", score: 7 },
    { title: "兔耳冒险谭", score: 7 },
    { title: "Twelve～世界から１３番目の君と～", score: 8.3 },
    { title: "Insult Order ~狂妄喵娘的快堕菜单~", score: 7.4 },
    { title: "玛珂娜·格拉穆拉与小仙铃", score: 7.2 },
    { title: "塔弦之雪", score: 7.5 },
    { title: "永远消失的幻想乡", score: 6.3 },
    { title: "堕落皇家圣处女", score: 5.8 },
    { title: "末世孤雄 Vol 0", score: 6.3 },
    { title: "Polar Star", score: 6.1 },
    { title: "爱欲姐妹洛丽塔", score: 6.5 },
    { title: "香子兰·审判之庭", score: 6.4 },
    { title: "幽灵镇少女 第一季", score: 7.9 },
    { title: "Iris+", score: 6.4 },
    { title: "とらぶるだいあり～・しすたぁ", score: 7.1 },
    { title: "まり∽くり -Ｒ- ～Queen Save the God ♪～", score: 6.8 },
    { title: "灼灼其华", score: 7.3 },
    { title: "真昼の暗黒", score: 7.6 },
    { title: "彼女は時のねじを逆向きに回した", score: 6.2 },
    { title: "欲都孤儿", score: 7.5 },
  ],
  "2019": [
    { title: "死月妖花～四月八日～", score: 9 },
    { title: "美好国度的建设方略", score: 7.1 },
    { title: "东方月神夜", score: 7.4 },
    { title: "夏日狂想曲：乡间的难忘回忆", score: 7.2 },
    { title: "シニシスタ SiNiSistar", score: 6.6 },
    { title: "远海咏叹调", score: 6.4 },
    { title: "AlexiA ~アレクシア~", score: 7.7 },
    { title: "东方幕华祭 春雪篇", score: 7.8 },
    { title: "FALL IN LABYRINTH -隶属的少女们-", score: 7.3 },
    { title: "Fanastasis", score: 8.6 },
    { title: "终末之子 -起源物语-", score: 6.6 },
    { title: "虚幻寓言：欲望的祭品", score: 7.4 },
    { title: "库贝尔的枷锁", score: 6.6 },
    { title: "治愈男性的机器人", score: 6.6 },
    { title: "臨界天のアズラーイール", score: 7 },
    { title: "蕾娜莉丝传奇", score: 7.3 },
    { title: "慰愛の詩", score: 6.2 },
    { title: "幻想乡萃夜祭", score: 6.2 },
    { title: "Lost Life", score: 5.9 },
    { title: "SEQUEL colony", score: 7.9 },
    { title: "炼金术士柯蕾特：精华炼成物语", score: 6.4 },
    { title: "新约帽子世界", score: 8.5 },
    { title: "ムートン・ノワール", score: 6.8 },
    { title: "TS魔法少女なお!2nd!!", score: 7.6 },
  ],
  "2020": [
    { title: "梅卡妮可 -兔子与水星之谣-", score: 7.7 },
    { title: "魔女魔少魔法魔", score: 6.9 },
    { title: "星空列车与白的旅行", score: 7.5 },
    { title: "蛇之命", score: 7.8 },
    { title: "魔法少女天穹法妮雅", score: 7.5 },
    { title: "祈愿诗篇", score: 7.4 },
    { title: "殺イコ・キネ死ス", score: 6.1 },
    { title: "魔斗姬莉斯缇亚", score: 6.6 },
    { title: "とらぶるだいあり～・てぃーちゃー", score: 7.2 },
    { title: "职场女友带回家", score: 5.9 },
    { title: "SUMMER-乡间性活", score: 6.2 },
    { title: "誘惑なまいきロリータ", score: 6.5 },
    { title: "クラブ・スーサイド", score: 6.7 },
    { title: "命运/尘埃帝国", score: 6.7 },
    { title: "僵尸×道士", score: 7.6 },
    { title: "夏色泡影", score: 6.8 },
    { title: "地下城军团-向魔王献上的少女肢体", score: 6.6 },
    { title: "东方归言录", score: 4.5 },
    { title: "NTR传说", score: 6 },
    { title: "ウウウルトラC", score: 7.7 },
    { title: "Conflict Girl", score: 7.1 },
    { title: "櫻庭邸の邪な幸福", score: 6.9 },
    { title: "隠さなきゃ", score: 6 },
    { title: "あわれは知らない子", score: 6.6 },
  ],
  "2021": [
    { title: "Demons Roots", score: 8.3 },
    { title: "东方夜雀食堂", score: 7.4 },
    { title: "圣骑士莉卡物语 白翼与淫翼姐妹", score: 7.7 },
    { title: "氤氲之白", score: 6.3 },
    { title: "魔法斗姬芙洛蒂娅", score: 7 },
    { title: "少女骑士救主记", score: 6.5 },
    { title: "雨霏霏，人非人", score: 5.8 },
    { title: "枝江往事", score: 5.6 },
    { title: "雨音和自动人形", score: 6.3 },
    { title: "背阴的日葵（荫处的向阳花）", score: 6.2 },
    { title: "用洗脑APP肆意玩弄狂妄大小姐", score: 5.9 },
    { title: "血、肉与混凝土", score: 7.2 },
    { title: "ブレイカーハーツ", score: 7.7 },
    { title: "榨精恶魔酱的五日寸止游戏~最后一天输掉的话会迎来悲惨结局哦~", score: 5.7 },
    { title: "芙蓉の浄土に安き給う", score: 5.2 },
    { title: "闪红的艾丽丝", score: 7.2 },
    { title: "淫界人柱阿拉卡～JK退魔师恐怖探索RPG～", score: 7.1 },
    { title: "迂回落幕的终章 —蝶与花的鸟笼—", score: 6.6 },
    { title: "东方冰之勇者记：序章", score: 7 },
    { title: "赤发鬼神", score: 6.7 },
    { title: "寝取新妻莫妮卡～傲娇的妻子和不正经的打工～", score: 5.6 },
    { title: "东方华彩乱战2 - 错乱空间", score: 6.3 },
    { title: "毁灭世界的魔法", score: 6.8 },
    { title: "东方虹龙洞 ～ Unconnected Marketeers.", score: 7.5 },
  ],
  "2022": [
    { title: "妹！相随 ~黑白世界的缤纷冒险~", score: 7.5 },
    { title: "传述之魔女", score: 7.6 },
    { title: "若、生命于明日落幕", score: 5.8 },
    { title: "前往遥远图勒的旅人", score: 7.6 },
    { title: "魔女在复仇之夜", score: 7.1 },
    { title: "夏日彼方", score: 6.5 },
    { title: "去人たちZERO Div1", score: 6.4 },
    { title: "梦狱之国的爱丽丝 ~猎奇密室逃脱游戏~", score: 5.5 },
    { title: "-HAPPY SAIN† SHEOL- ハッピーセイント・シェオル", score: 6 },
    { title: "ま～じゃんコネクト!", score: 6.4 },
    { title: "蜈蚣裁判", score: 7.2 },
    { title: "魔导士小奏的扶她地牢探险", score: 7.1 },
    { title: "Nebel Geisterjäger ~ 零号羔羊", score: 6 },
    { title: "青少年药物妄想杀人事件", score: 6.7 },
    { title: "喜欢上你的冒牌货", score: 5.8 },
    { title: "血根", score: 7.5 },
    { title: "淫习的幽世村~绝对不能曝光女性身分的时间~", score: 6.4 },
    { title: "最近の日常的不可思議 Monday Loop", score: 7 },
    { title: "莉可的不可思议差事", score: 6.4 },
    { title: "怠惰的怪獸公主不想工作", score: 5.9 },
    { title: "エリスディスノミア", score: 6.9 },
    { title: "不香の花 - Snow Flower", score: 7 },
    { title: "女忍花梨", score: 7 },
    { title: "光与影的二重身", score: 5.5 },
  ],
  "2023": [
    { title: "只属于我的神秘规则！赢了女训练家的话H是理所当然的", score: 7.5 },
    { title: "享受这间餐厅吧", score: 7.3 },
    { title: "剧透太多的RPG - 最后的敌人的真实身份是勇者的爸爸 -", score: 6.7 },
    { title: "Heaven For Death", score: 7 },
    { title: "我对小小老师一见钟情了", score: 6.1 },
    { title: "敬业女仆咲夜", score: 6.8 },
    { title: "幸福宅女的养成方法", score: 6 },
    { title: "艾米莉·布兰切多次堕落～与魔法学院重复一周～", score: 6.7 },
    { title: "女性交流", score: 7 },
    { title: "Violated Princess", score: 7.1 },
    { title: "防身术道场 秘密的NTR课程", score: 5.6 },
    { title: "理想中的父親～和心愛的女兒一起生活～", score: 6 },
    { title: "月之少女、河中天使、成神之刻。", score: 6.3 },
    { title: "清晨五点弹奏钢琴", score: 6 },
    { title: "这份恋情、迎来终焉、", score: 5.9 },
    { title: "冬日狂想曲", score: 7.5 },
    { title: "えちクラ～えっち&クラフト～", score: 6.8 },
    { title: "零月的拉芙拉", score: 8.1 },
    { title: "ソルルイ -after mini-", score: 7.7 },
    { title: "东北之夏", score: 5.8 },
    { title: "喧嚣归于静寂", score: 7.1 },
    { title: "梦魇骑士 ~圣洁少女与堕落魔法~", score: 6.3 },
    { title: "忍堕－女忍调教", score: 6.5 },
    { title: "夏空あすてりずむ", score: 0 },
  ],
  "2024": [
    { title: "鼓手余命十日谭", score: 7.6 },
    { title: "星之终途后日谈：渺茫希望的日记", score: 7.4 },
    { title: "宝石少女 1st.cut:The Reason She Must Perish", score: 6.8 },
    { title: "东方冰之勇者记 ~ Touhou Hero of Ice Fairy", score: 7.4 },
    { title: "望却のエディシウス", score: 6.1 },
    { title: "Folie Fatale 致命至爱", score: 5.7 },
    { title: "勇者大战魔物娘RPG 终章", score: 8.8 },
    { title: "情欲古式按摩店 -沉迷秘密服务的母女们-", score: 5.5 },
    { title: "植物大战僵尸杂交版", score: 6.5 },
    { title: "黄昏的乐园与被染红的天使", score: 7.5 },
    { title: "Sisters Connect 想要诉说的心意", score: 5.6 },
    { title: "大秽-前篇-", score: 6.9 },
    { title: "アリアサキュズム", score: 7 },
    { title: "DECOY 群青の魔女", score: 6.2 },
    { title: "鉛の棍棒", score: 7.6 },
    { title: "我的姐姐被恶霸强奸", score: 5.6 },
    { title: "It was a human.", score: 6.2 },
    { title: "グッドバイ", score: 6.8 },
    { title: "迷宮都市アサイラム", score: 6.8 },
    { title: "我在平行世界的班級", score: 6.2 },
    { title: "ミラージュの離反", score: 7.5 },
    { title: "夜明けを待つ、星たちへ。", score: 6.1 },
    { title: "夏色泡影After", score: 6.7 },
    { title: "阁楼里的眠姬", score: 7.3 },
  ],
};

export default data;
