type Data = {
  [key: string]: { title: string; score: number }[];
};

const data: Data = {
  "2000": [
    { title: "AIR", score: 8.4 },
    { title: "月姬", score: 8.2 },
    { title: "第七夜：无限轮回的终结", score: 7.2 },
    { title: "书淫，或是已失去的梦之物语。", score: 7.2 },
    { title: "幻灵镇魂曲", score: 8.2 },
    { title: "银色", score: 7.3 },
    { title: "无颜之月", score: 7.2 },
    { title: "sense off ～a sacred story in the wind～", score: 7.2 },
    { title: "奴隶市场", score: 7.7 },
    { title: "二重影", score: 6.9 },
    { title: "黑暗圣经 -沃普尔吉斯之夜-", score: 7.1 },
    { title: "2nd LOVE", score: 6.8 },
    { title: "梦之翼", score: 7.2 },
    { title: "化石之歌", score: 7.5 },
    { title: "果てしなく青い、この空の下で…。", score: 6.9 },
    { title: "Canvas ～セピア色のモチーフ～", score: 7.1 },
    { title: "él", score: 7.3 },
    { title: "螺旋回廊", score: 6.6 },
    { title: "花历", score: 6.8 },
    { title: "夜行侦探 零", score: 7.2 },
    { title: "久远之绊 再临诏", score: 7.7 },
    { title: "Treating2U", score: 7.6 },
    { title: "星空☆ぷらねっと", score: 6.6 },
    { title: "机甲战线", score: 6.7 },
  ],
  "2001": [
    { title: "家族计划", score: 8.4 },
    { title: "对你说再见～comment te dire adieu～", score: 7.5 },
    { title: "秋之回忆2", score: 8.1 },
    { title: "自杀的101种方法", score: 6.2 },
    { title: "你所期望的永远", score: 7.8 },
    { title: "水夏", score: 7.1 },
    { title: "歌月十夜", score: 7.5 },
    { title: "月姬 PLUS-DISC", score: 6.6 },
    { title: "鬼作", score: 7.6 },
    { title: "水色", score: 6.7 },
    { title: "Crescendo ～永遠だと思っていたあの頃～", score: 7.6 },
    { title: "情归故里", score: 7.1 },
    { title: "潘多拉之梦", score: 7.1 },
    { title: "思念的碎片 -Close to-", score: 7 },
    { title: "吸血歼鬼维德戈尼亚", score: 6.7 },
    { title: "大恶司", score: 7.6 },
    { title: "月阳炎", score: 6.9 },
    { title: "苍青色的月光", score: 6.9 },
    { title: "秋桜の空に", score: 7.9 },
    { title: "幻燐的姬将军", score: 6.7 },
    { title: "樱花大战3 ～巴黎在燃烧吗～", score: 8.2 },
    { title: "Renaissance", score: 7.7 },
    { title: "出云战记", score: 6.4 },
    { title: "红磨坊", score: 7.1 },
  ],
  "2002": [
    { title: "时空轮回", score: 9.1 },
    { title: "腐姬", score: 8.3 },
    { title: "传颂之物", score: 7.8 },
    { title: "鬼哭街", score: 7.3 },
    { title: "BALDR FORCE", score: 7.9 },
    { title: "兰斯5D：孤单的女孩子", score: 5.7 },
    { title: "沦为回忆的你 ~秋之回忆~", score: 6.7 },
    { title: "肢体洗", score: 6.6 },
    { title: "欲望学院", score: 6.2 },
    { title: "水月 -すいげつ-", score: 7.1 },
    { title: "天使小夜曲", score: 7.4 },
    { title: "白诘草话", score: 7.5 },
    { title: "寒蝉鸣泣之时 鬼隐篇", score: 7.6 },
    { title: "繁花落舞恋如樱", score: 7.6 },
    { title: "妻中蜜", score: 6.2 },
    { title: "情书", score: 6.6 },
    { title: "初音岛", score: 7.1 },
    { title: "寒蝉鸣泣之时 绵流篇", score: 8.1 },
    { title: "ヤミと帽子と本の旅人", score: 7.7 },
    { title: "公主假日", score: 6.1 },
    { title: "风-心之呼吸", score: 6.7 },
    { title: "Binary pot", score: 5.9 },
    { title: "雪融化的时刻", score: 6.5 },
    { title: "睡莲", score: 7.2 },
  ],
  "2003": [
    { title: "沙耶之歌", score: 7.7 },
    { title: "CROSS†CHANNEL", score: 8.5 },
    { title: "Muv-Luv", score: 6.7 },
    { title: "120日元之冬", score: 7.5 },
    { title: "120日元之夏", score: 6.7 },
    { title: "河原崎家的一族2", score: 7.8 },
    { title: "没有天使的12月", score: 7.2 },
    { title: "斩魔大圣Demonbane", score: 7.4 },
    { title: "秋之回忆 二重奏", score: 7.9 },
    { title: "女仆咖啡巧克拉", score: 7 },
    { title: "V.G.NEO", score: 7.6 },
    { title: "永远的艾塞莉娅", score: 8.2 },
    { title: "CANNONBALL：猫猫疯狂大赛车", score: 7.9 },
    { title: "あした出逢った少女", score: 7.6 },
    { title: "雪歌", score: 7.1 },
    { title: "朱 -Aka-", score: 6.8 },
    { title: "Petit Fleur～拂过小镇的旋律之风～", score: 6.7 },
    { title: "LOVERS～恋に落ちたら…～", score: 7.4 },
    { title: "夏梦夜话", score: 7.5 },
    { title: "夜月东升•暮日西沉～Operation Sanctuary～", score: 6.6 },
    { title: "海からくるもの", score: 7.4 },
    { title: "从此方到彼方", score: 7 },
    { title: "幻燐的姫将军2：引导灵魂的族谱", score: 7.7 },
    { title: "大番长", score: 7.5 },
  ],
  "2004": [
    { title: "CLANNAD", score: 8.9 },
    { title: "Fate/stay night", score: 8.3 },
    { title: "星之梦", score: 8 },
    { title: "交响乐之雨", score: 8.5 },
    { title: "Remember11：无限轮回的时光", score: 8.9 },
    { title: "家族计划~再开~", score: 8.7 },
    { title: "狂欢节", score: 7.5 },
    { title: "Forest", score: 8.6 },
    { title: "3days ～在逝去时间的另一端～", score: 6.7 },
    { title: "兰斯6 - 赛斯崩坏 -", score: 7.5 },
    { title: "秋之回忆：从今以后", score: 7.7 },
    { title: "寒蝉鸣泣之时", score: 8.2 },
    { title: "乐园～一如既往的我。的存在～", score: 8.1 },
    { title: "MinDeaD BlooD：献给支配者的狂死曲", score: 7.6 },
    { title: "神树之馆", score: 7.7 },
    { title: "SHUFFLE！", score: 6.4 },
    { title: "红线", score: 7.5 },
    { title: "初音岛 P.C.", score: 6.8 },
    { title: "春天的足音", score: 7.7 },
    { title: "ToHeart2", score: 7.5 },
    { title: "四重奏！", score: 7.4 },
    { title: "那一天，去往何方", score: 7 },
    { title: "巢作之龙", score: 6.9 },
    { title: "弹珠汽水", score: 7 },
  ],
  "2005": [
    { title: "水仙", score: 8.5 },
    { title: "车轮之国、向日葵的少女", score: 8.1 },
    { title: "天鹅之歌", score: 8.1 },
    { title: "女仆咖啡帕露菲", score: 8 },
    { title: "恋狱～月狂病～", score: 7.5 },
    { title: "智代After ～It's a Wonderful Life～", score: 7.3 },
    { title: "Fate/hollow ataraxia", score: 7.8 },
    { title: "120日元之春", score: 7.2 },
    { title: "最后的现在", score: 8.7 },
    { title: "梦见之药", score: 7.4 },
    { title: "120日元之秋", score: 6.6 },
    { title: "日在校园", score: 7.1 },
    { title: "夜明前的琉璃色", score: 6.8 },
    { title: "灯穗奇谭", score: 6.9 },
    { title: "ToHeart2 XRATED", score: 7.6 },
    { title: "秋之回忆5：中断的胶片", score: 7.2 },
    { title: "尘骸魔京", score: 7.4 },
    { title: "少女爱上姐姐", score: 7 },
    { title: "刃鸣散", score: 7 },
    { title: "Sanarara", score: 7.5 },
    { title: "我不是天使", score: 7.2 },
    { title: "娇蛮之吻", score: 7.2 },
    { title: "秋之回忆：雨后", score: 6.9 },
    { title: "妖人", score: 7.6 },
  ],
  "2006": [
    { title: "Muv-Luv Alternative", score: 8.8 },
    { title: "悠久之翼-前篇", score: 7.6 },
    { title: "遥仰凰华", score: 7.5 },
    { title: "青空下的约定", score: 7.8 },
    { title: "战国兰斯", score: 8.3 },
    { title: "I/O", score: 8.1 },
    { title: "雪影", score: 7.5 },
    { title: "离开的人们", score: 7.5 },
    { title: "H2O ～FOOTPRINTS IN THE SAND～", score: 7 },
    { title: "寒蝉鸣泣之时解", score: 8.4 },
    { title: "假如明日天放晴", score: 7.1 },
    { title: "Gore Screaming Show", score: 7 },
    { title: "EXTRAVAGANZA ～蟲愛でる少女～", score: 7.6 },
    { title: "Fossette - Cafe au Le Ciel Bleu -", score: 7.5 },
    { title: "亲吻那片花瓣", score: 6.4 },
    { title: "她们的流仪", score: 7.1 },
    { title: "Scarlett ～スカーレット～", score: 7.4 },
    { title: "望见青空之丘", score: 6.4 },
    { title: "秋之回忆：从今以后again", score: 7.2 },
    { title: "四叶草", score: 6.9 },
    { title: "七色星露", score: 6.7 },
    { title: "管乐恋曲！~The bonds of melody~", score: 5.9 },
    { title: "妻管严", score: 7.6 },
    { title: "凝视那侧脸 ~A Profile 完全版~", score: 7.2 },
  ],
  "2007": [
    { title: "水仙2", score: 8.2 },
    { title: "KIRA☆KIRA 煌煌舞台", score: 8.5 },
    { title: "车轮之国、悠久的少年少女", score: 7.7 },
    { title: "海猫鸣泣之时", score: 8.4 },
    { title: "世界上最NG的恋爱", score: 7.5 },
    { title: "续·杀戮之姜戈—地狱通缉犯—", score: 8.2 },
    { title: "Little Busters!", score: 8.3 },
    { title: "电波消逝之日", score: 5.3 },
    { title: "染红的街道", score: 6.7 },
    { title: "明日的世界", score: 7 },
    { title: "赫炎的印加诺克 ～何等美好的人们～", score: 7.5 },
    { title: "Aster", score: 7.2 },
    { title: "终有一日愿遂彼空", score: 7.1 },
    { title: "片羽", score: 7.5 },
    { title: "和之匣", score: 6.4 },
    { title: "盛开的钢琴之森下", score: 6.8 },
    { title: "亲吻那片花瓣 ～与你的恋人纽带～", score: 7 },
    { title: "为与明日君相逢", score: 6.9 },
    { title: "向日葵", score: 8 },
    { title: "恋爱少女与守护之盾", score: 6.7 },
    { title: "世界树与恋爱魔法使", score: 6.4 },
    { title: "月光下的CARNEVALE", score: 7.2 },
    { title: "E×E", score: 5.6 },
    { title: "亲吻那片花瓣：我的王子大人", score: 6.4 },
  ],
  "2008": [
    { title: "G弦上的魔王", score: 7.9 },
    { title: "缘之空", score: 7 },
    { title: "媚肉之香", score: 7.9 },
    { title: "壳之少女", score: 7.6 },
    { title: "Little Busters! EX", score: 8.5 },
    { title: "悠久之翼-后篇", score: 8.4 },
    { title: "混沌头", score: 7 },
    { title: "夏空彼方", score: 7.3 },
    { title: "11eyes -罪与罚与赎的少女-", score: 7.2 },
    { title: "晓之护卫", score: 7 },
    { title: "秋之回忆6：三角波动", score: 6.8 },
    { title: "FORTUNE ARTERIAL", score: 7.1 },
    { title: "晓之护卫～主角们的休息日～", score: 6.7 },
    { title: "你所期望的永远 ～Latest Edition～", score: 7.9 },
    { title: "媚肉之香番外篇", score: 6.6 },
    { title: "智以泪聚", score: 7.5 },
    { title: "游魂-Kiss on my Deity-", score: 6.7 },
    { title: "MYTH", score: 7.7 },
    { title: "超极糖果～王道自有王道的理由～", score: 7.1 },
    { title: "战女神ZERO", score: 8.2 },
    { title: "公主恋人", score: 6.1 },
    { title: "漆黑的夏尔诺斯 ～何等美好的明日～", score: 7.4 },
    { title: "初音岛2 P.C.", score: 7.7 },
    { title: "彼女×彼女×彼女～三姉妹とのドキドキ共同生活～", score: 6.9 },
  ],
  "2009": [
    { title: "eden* They were only two, on the planet.", score: 7.9 },
    { title: "命运石之门", score: 8.9 },
    { title: "装甲恶鬼村正", score: 8.6 },
    { title: "BALDR SKY Dive2 "RECORDARE"", score: 8.8 },
    { title: "BALDR SKY Dive1 "LostMemory"", score: 8.5 },
    { title: "纯白交响曲", score: 7.2 },
    { title: "星空的记忆 -Wish upon a shooting star", score: 7.8 },
    { title: "天神乱漫 -LUCKY or UNLUCKY!?-", score: 6.8 },
    { title: "从晴朗的朝色泛起之际开始", score: 7.6 },
    { title: "悠之空", score: 6.5 },
    { title: "我们没有翅膀", score: 8.4 },
    { title: "兰斯02~反叛的少女们~", score: 5.9 },
    { title: "黑暗之蓝", score: 5.4 },
    { title: "死神之吻乃离别之味", score: 6.6 },
    { title: "海猫鸣泣之时散", score: 8.6 },
    { title: "水仙3", score: 7.3 },
    { title: "圣诞之吻", score: 7.9 },
    { title: "认真和我恋爱", score: 7.9 },
    { title: "Flyable Heart", score: 7 },
    { title: "花与乙女的祝福", score: 6.8 },
    { title: "夏之雨", score: 6.9 },
    { title: "夏梦渚", score: 7.4 },
    { title: "幼驯染是大总统", score: 6.3 },
    { title: "白雪～七凭之祭～", score: 6 },
  ],
  "2010": [
    { title: "美好的每一天 ～不连续的存在～", score: 8.8 },
    { title: "白色相簿2 序章", score: 8.2 },
    { title: "黄昏的禁忌之药", score: 7.5 },
    { title: "实妹相伴的大泉君", score: 7.1 },
    { title: "寻找失去的未来", score: 6.6 },
    { title: "恋爱和选举和巧克力", score: 6.6 },
    { title: "白色相簿：编缀的冬日回忆", score: 7.3 },
    { title: "星空的记忆 永恒之心", score: 7.6 },
    { title: "海猫鸣泣之时~魔女与推理的轮舞曲~", score: 8.7 },
    { title: "Noble Works", score: 6.6 },
    { title: "架向星空之桥", score: 6.4 },
    { title: "晓之护卫 ～罪孽深重的末世论～", score: 7 },
    { title: "人间残渣", score: 6.9 },
    { title: "暗之部屋", score: 7.7 },
    { title: "库特wafter", score: 7 },
    { title: "BALDR SKY DiveX "DREAM WORLD"", score: 7.6 },
    { title: "天使的星期日", score: 7.4 },
    { title: "日在校园 HQ", score: 7 },
    { title: "Tiny Dungeon ～BLACK and WHITE～", score: 6.4 },
    { title: "装甲恶鬼村正 邪念篇", score: 6.5 },
    { title: "秋之回忆：勾指起誓的记忆", score: 7.1 },
    { title: "天神乱漫 Happy Go Lucky!!", score: 6.8 },
    { title: "君之余影静静地摇曳着", score: 7.5 },
    { title: "ef - a fairy tale of the two.", score: 8.1 },
  ],
  "2011": [
    { title: "秽翼的尤斯蒂娅", score: 8.3 },
    { title: "白色相簿2 终章", score: 9 },
    { title: "Rewrite", score: 8.6 },
    { title: "美少女万华镜 -被诅咒的传说少女-", score: 6.9 },
    { title: "euphoria", score: 7.2 },
    { title: "五彩斑斓的世界", score: 7.5 },
    { title: "妹调教日记", score: 4.9 },
    { title: "灰色的果实", score: 7.8 },
    { title: "无限炼奸 ~不死舞姬的凌辱轮舞曲~", score: 7.5 },
    { title: "女装山脉", score: 6.1 },
    { title: "LOVELY×CATION", score: 6.7 },
    { title: "我的女友是蓝领／她的作为，我的遭遇／巨乳妻完全捕获计划／我老婆被那家伙睡了。", score: 7.5 },
    { title: "恋爱0公里", score: 6.9 },
    { title: "鬼哭街 泪尽铃音响", score: 7.3 },
    { title: "谁杀死了知更鸟", score: 5.1 },
    { title: "兰斯8", score: 7.4 },
    { title: "鬼的捉迷藏！", score: 6.7 },
    { title: "海猫鸣泣之时散～真实与幻想的夜想曲～", score: 8.7 },
    { title: "NOeSIS-虚伪记忆的物语-", score: 7.4 },
    { title: "绝对高潮☆性器大发明!!―捕获学园处女的多样工口道具―", score: 6.5 },
    { title: "不要践踏天使的羽毛", score: 7 },
    { title: "纯白交响曲 六出飞花", score: 7.7 },
    { title: "突然之间发现我已恋上你", score: 6.4 },
    { title: "命运石之门 比翼恋理的爱人", score: 6.8 },
  ],
  "2012": [
    { title: "近月少女的礼仪", score: 7.7 },
    { title: "魔法使之夜", score: 8.6 },
    { title: "初雪樱", score: 7.6 },
    { title: "美少女万华镜 -勿忘草与永远的少女-", score: 6.8 },
    { title: "海市蜃楼之馆", score: 8.4 },
    { title: "DRACU-RIOT!", score: 7 },
    { title: "白色相簿2 幸福的彼端", score: 8.9 },
    { title: "五彩斑斓的曙光", score: 7.8 },
    { title: "时钟机关的Ley-line-黄昏时刻的境界线-", score: 6.7 },
    { title: "Rewrite Harvest festa!", score: 7.2 },
    { title: "夏空的英仙座", score: 6.3 },
    { title: "在这苍穹展翅", score: 7.4 },
    { title: "幻灵镇魂曲", score: 8.2 },
    { title: "硬要无视与你的未来", score: 7.1 },
    { title: "灰色的迷宫", score: 7.7 },
    { title: "春开，意遥遥。", score: 7.5 },
    { title: "すぴぱら STORY ＃01 - Spring Has Come！", score: 7.3 },
    { title: "现在就想告诉哥哥，我是妹妹！", score: 6.9 },
    { title: "少女编织爱的画布", score: 6.9 },
    { title: "古色迷宫轮舞曲 ～HISTOIRE DE DESTIN～", score: 7.2 },
    { title: "初恋1/1", score: 6.6 },
    { title: "Root Double -Before Crime  After Days-", score: 7.8 },
    { title: "幼驯染与十年之夏", score: 7 },
    { title: "仓野家的双胞胎故事", score: 5.9 },
  ],
  "2013": [
    { title: "你和她和她的恋爱。", score: 7.4 },
    { title: "少女理论及其周边 -巴黎学院篇-", score: 8 },
    { title: "大图书馆的牧羊人", score: 7.4 },
    { title: "フレラバ ～Friend to Lover～", score: 7.8 },
    { title: "向日葵的教会与长长的暑假", score: 7.7 },
    { title: "虚之少女", score: 7.4 },
    { title: "兰斯01 寻找小光", score: 7 },
    { title: "天色幻想岛", score: 6 },
    { title: "时钟机关的Ley-line-残影之夜将明时-", score: 7.8 },
    { title: "灰色的乐园", score: 7.8 },
    { title: "幸福噩梦", score: 7 },
    { title: "LOVELY×CATION2", score: 6.8 },
    { title: "LOVESICK PUPPIES -我们为了恋爱而诞生-", score: 7 },
    { title: "妹调教日记√happy end & another", score: 5.6 },
    { title: "魔导巧壳", score: 7.4 },
    { title: "sisters ～夏天最后一日～ Ultra Edition", score: 7.1 },
    { title: "忠臣藏46＋1", score: 8.2 },
    { title: "卡卢玛卢卡＊同好会", score: 6.5 },
    { title: "大图书馆的牧羊人～放学后的尾巴时光～", score: 6.3 },
    { title: "命运石之门 线形拘束的树状图", score: 7.2 },
    { title: "茂伸奇谈-Happy End-", score: 7 },
    { title: "回忆录", score: 7.1 },
    { title: "我成为天使的理由", score: 7.1 },
    { title: "圣娼女 ～性奴育成学园～", score: 6.5 },
  ],
  "2014": [
    { title: "苍之彼方的四重奏", score: 7.9 },
    { title: "纸上魔法使", score: 7.9 },
    { title: "混沌子", score: 8.4 },
    { title: "幸运草的约定", score: 7.2 },
    { title: "ネコぱら vol.1 ソレイユ開店しました！", score: 6.1 },
    { title: "美少女万华镜 -献给曾是少女的你-", score: 5.8 },
    { title: "魔女恋爱日记", score: 7.3 },
    { title: "若能与你再次相见", score: 7.3 },
    { title: "近月少女的礼仪2", score: 6.8 },
    { title: "兰斯9 赫尔曼革命", score: 8.2 },
    { title: "FLOWERS 春篇", score: 7.3 },
    { title: "晴霁之后定是菜花盛开的好天气", score: 6.4 },
    { title: "白色相簿2 mini After Story", score: 7.5 },
    { title: "恋花绽放樱飞时", score: 6.2 },
    { title: "航迹云的彼方", score: 7.6 },
    { title: "高考恋爱100天", score: 6.6 },
    { title: "星辰恋曲的白色永恒", score: 7.2 },
    { title: "她的圣域", score: 6.2 },
    { title: "淑女同萌！", score: 6.9 },
    { title: "雨恋", score: 6.6 },
    { title: "慕情之心今随君作伴", score: 7.2 },
    { title: "PRIMAL×HEARTS", score: 6.9 },
    { title: "友爱俱乐部", score: 5.7 },
    { title: "大图书馆的牧羊人 -Dreaming Sheep-", score: 7.1 },
  ],
  "2015": [
    { title: "樱之诗 - 在樱花之森上飞舞", score: 8.8 },
    { title: "魔女的夜宴", score: 7.2 },
    { title: "想要传达给你的爱恋", score: 7.2 },
    { title: "美少女万华镜 -为神所创的少女们-", score: 7.2 },
    { title: "人狼村之谜", score: 8.2 },
    { title: "永不落幕的前奏诗", score: 7.2 },
    { title: "命运石之门 0", score: 7.9 },
    { title: "末世孤雄 Vol 1", score: 7 },
    { title: "兰斯03 利萨斯陷落", score: 8.2 },
    { title: "时钟机关的Ley-line-朝雾中飘零之花-", score: 7.9 },
    { title: "夏娃年代记", score: 7.5 },
    { title: "抬头看看吧，看那天上的繁星", score: 7.4 },
    { title: "与你心相连", score: 7.5 },
    { title: "与奴隶的生活 -Teaching Feeling-", score: 6.3 },
    { title: "传颂之物-虚伪的假面-", score: 8 },
    { title: "花咲workspring！", score: 6.9 },
    { title: "FLOWERS 夏篇", score: 8.1 },
    { title: "你朱眸里的五彩世界", score: 7 },
    { title: "海市蜃楼之馆 -A Requiem for Innocence-", score: 8.5 },
    { title: "ネコぱら vol.0 水無月ネコたちの日常！", score: 5.8 },
    { title: "Angel Beats! 1st beat", score: 7.2 },
    { title: "妹的圣域", score: 6.2 },
    { title: "柯罗的怀表", score: 6.7 },
    { title: "向日葵：天空鹅卵石", score: 7.8 },
  ],
  "2016": [
    { title: "千恋＊万花", score: 6.9 },
    { title: "ISLAND", score: 7.8 },
    { title: "天津罪", score: 7.6 },
    { title: "少女＊领域", score: 6.7 },
    { title: "永不枯萎的世界与终结之花", score: 6.7 },
    { title: "野良与皇女与流浪猫之心", score: 7.2 },
    { title: "逝去的你、于馆中萌生的憎恶", score: 6.3 },
    { title: "千之刃涛、桃花染之皇姬", score: 6.8 },
    { title: "银色遥远", score: 7.2 },
    { title: "爱上火车", score: 6.8 },
    { title: "Re:LieF 〜献给亲爱的你〜", score: 6.9 },
    { title: "生命的备件", score: 6.7 },
    { title: "海底", score: 8.5 },
    { title: "夏之锁", score: 6.7 },
    { title: "少女理论及其之后的周边 -美好年代篇-", score: 7.3 },
    { title: "花之天使的夏日恋歌", score: 7.2 },
    { title: "来自昏暗的时间尽头", score: 7.4 },
    { title: "传颂之物-二人之白皇-", score: 8.2 },
    { title: "ネコぱら vol.2 姉妹ネコのシュクレ", score: 6.1 },
    { title: "樱之杜†净梦者", score: 6.8 },
    { title: "FLOWERS 秋篇", score: 8.2 },
    { title: "ラムネーション！", score: 6.9 },
    { title: "与她＊心渐近", score: 7.2 },
    { title: "青春×好奇相伴的三角恋爱", score: 6.6 },
  ],
  "2017": [
    { title: "9-nine-九次九日九重色", score: 6.4 },
    { title: "金辉恋曲四重奏", score: 7.6 },
    { title: "流景之海的艾佩理雅", score: 8 },
    { title: "美少女万华镜 -罪与罚的少女-", score: 6.9 },
    { title: "心跳文学部！", score: 6.8 },
    { title: "月影魅像-解放之羽-", score: 7 },
    { title: "突然＊恋人", score: 7.5 },
    { title: "水葬银货的伊斯特利亚", score: 7.3 },
    { title: "牵绊闪耀的恋之伊吕波", score: 6.4 },
    { title: "青鸟", score: 7.4 },
    { title: "三色△绘恋", score: 5.8 },
    { title: "甜糖热恋", score: 6.8 },
    { title: "苍之彼方的四重奏 EXTRA1", score: 7.2 },
    { title: "牛顿与苹果树", score: 6.4 },
    { title: "野良与皇女与流浪猫之心2", score: 7.5 },
    { title: "回家前都算是棉花糖", score: 6.5 },
    { title: "天结城堡大师", score: 7.5 },
    { title: "任性HighSpec", score: 6.7 },
    { title: "ネコぱら vol.3 ネコたちのアロマティゼ", score: 6.1 },
    { title: "ChronoBox -クロノボックス-", score: 6.8 },
    { title: "在世界尽头咏唱恋曲的少女YU-NO 重制版", score: 8.1 },
    { title: "7days—与你共度的七日间", score: 7.3 },
    { title: "樱舞落花恋模样", score: 5.4 },
    { title: "夜巡る、ボクらの迷子教室", score: 7 },
  ],
  "2018": [
    { title: "Summer Pockets", score: 8.3 },
    { title: "RIDDLE JOKER", score: 6.6 },
    { title: "9-nine-天色天歌天籁音", score: 7.2 },
    { title: "抜きゲーみたいな島に住んでる貧乳はどうすりゃいいですか？", score: 7.5 },
    { title: "兰斯10 决战", score: 9.3 },
    { title: "寄宿之恋", score: 6.8 },
    { title: "奇异恩典·圣夜的小镇", score: 7.5 },
    { title: "5分钟的邂逅！时间停止与不可避免的命运！", score: 6.5 },
    { title: "乌有乡", score: 7.3 },
    { title: "哥哥，早上起床之前都要抱紧我哦！", score: 6.4 },
    { title: "如月真绫的诱惑", score: 6.5 },
    { title: "末世孤雄 Vol 2", score: 6.9 },
    { title: "末世孤雄 Vol 3", score: 7 },
    { title: "告别回忆 -无垢少女-", score: 7.2 },
    { title: "美好的每一天 ～不连续的存在～全语音HD版", score: 9 },
    { title: "Butterfly Seeker - 寻蝶者", score: 7.2 },
    { title: "神待少女纱波", score: 6.6 },
    { title: "封缄之都古拉塞斯塔", score: 7 },
    { title: "丑小鸭与文字祸", score: 6.3 },
    { title: "宿星的女朋友-destiny star girlfriend-", score: 7 },
    { title: "未来广播与人工鸽", score: 6.6 },
    { title: "吹弹！丰盈！波涛汹涌！异世界魔法学园！", score: 6.8 },
    { title: "末世孤雄 Vol 0", score: 6.3 },
    { title: "1room -离家出走的少女-", score: 6.6 },
  ],
  "2019": [
    { title: "9-nine-春色春恋春熙风", score: 6.9 },
    { title: "星光咖啡馆与死神之蝶", score: 6.4 },
    { title: "樱花、萌放。-as the Night's, Reincarnation-", score: 8.3 },
    { title: "青空下的加缪", score: 7.1 },
    { title: "抜きゲーみたいな島に住んでる貧乳はどうすりゃいいですか？2", score: 8.1 },
    { title: "恋愛、借りちゃいました", score: 6.8 },
    { title: "异想魅惑", score: 7.2 },
    { title: "金辉恋曲四重奏 -Golden Time-", score: 7.5 },
    { title: "青夏轨迹", score: 7 },
    { title: "SorceressAlive!～世界末日陨落之星～", score: 7.3 },
    { title: "Christmas Tina -泡沫冬景-", score: 6.9 },
    { title: "在月之彼岸邂逅", score: 7.4 },
    { title: "スタディ§ステディ", score: 6.8 },
    { title: "絆きらめく恋いろは -椿恋歌-", score: 6.7 },
    { title: "玉响未来", score: 7 },
    { title: "MUSICUS!", score: 8.5 },
    { title: "流星世界演绎者", score: 6.9 },
    { title: "真爱的百合被染成红色", score: 5.4 },
    { title: "吹弹！丰盈！波涛汹涌 超情色APP学院", score: 7 },
    { title: "pieces/候鸟的梦", score: 7 },
    { title: "夏娃年代记2", score: 6.9 },
    { title: "千之刃涛、桃花染之皇姬 -柳暗花明-", score: 6.4 },
    { title: "Sugar*Style", score: 6.8 },
    { title: "哥哥，早上起床之前都要抱紧我哦！晚上睡觉之前做更多色色的事吧！", score: 6.5 },
  ],
  "2020": [
    { title: "亚托莉 -我挚爱的时光-", score: 7.2 },
    { title: "Summer Pockets REFLECTION BLUE", score: 8.4 },
    { title: "9-nine-雪色雪花雪之痕", score: 7.7 },
    { title: "星空列车与白的旅行", score: 7.5 },
    { title: "常轨脱离Creative", score: 6.9 },
    { title: "樱色之云绯色之恋", score: 7.7 },
    { title: "美少女万华镜 -理与迷宫的少女-", score: 7.4 },
    { title: "丸子与银河龙", score: 7.5 },
    { title: "多娜多娜 一起干坏事吧", score: 7.4 },
    { title: "白日梦的构想图", score: 7.5 },
    { title: "甜蜜女友2", score: 7.4 },
    { title: "终之空 remake", score: 7.6 },
    { title: "爱上火车-Last Run!!-", score: 7.2 },
    { title: "天之少女", score: 8.2 },
    { title: "保健室的老师与沉迷吹泡泡的助手", score: 7.2 },
    { title: "放学后的灰姑娘", score: 7.1 },
    { title: "爱因斯坦携爱敬上", score: 5.8 },
    { title: "恋爱X决胜战", score: 6.4 },
    { title: "绽放★青春全力向前冲！", score: 6.1 },
    { title: "巧克甜恋", score: 6.3 },
    { title: "恋爱绮谭~不存在的夏天~", score: 6.7 },
    { title: "Saleté", score: 7.2 },
    { title: "一生推不如一生恋", score: 6 },
    { title: "红月摇曳的恋之星火", score: 7 },
  ],
  "2021": [
    { title: "9-nine- 新章", score: 6.1 },
    { title: "冥契的牧神节", score: 7.6 },
    { title: "月姬 -A piece of blue glass moon-", score: 8.2 },
    { title: "时廻者", score: 6.1 },
    { title: "ROLEPLAYER：小粥姐妹的黏膜游戏！", score: 7.1 },
    { title: "冬暮川滚滚", score: 7.3 },
    { title: "Monkeys!¡", score: 7.2 },
    { title: "创作彼女的恋爱方程式", score: 6.1 },
    { title: "PARQUET", score: 5.7 },
    { title: "海猫鸣泣之时咲～猫箱和梦想的交响曲～", score: 8.8 },
    { title: "LUNARiA -Virtualized Moonchild-", score: 6.7 },
    { title: "巧克甜恋2", score: 6.8 },
    { title: "我的恋天使太废柴了好可怕", score: 6.1 },
    { title: "同级生 重制版", score: 7 },
    { title: "小白兔电商", score: 6.6 },
    { title: "纯爱咖啡厅～帕露菲重制版～", score: 7.7 },
    { title: "日向千寻的工作总是做不久", score: 6.6 },
    { title: "吹弹！丰盈！波涛汹涌！异世界魅魔学园！", score: 7.2 },
    { title: "心跳文学部 Plus!", score: 6.8 },
    { title: "久那土国记", score: 6.6 },
    { title: "爱因斯坦携爱敬上 APOLLOCRISIS", score: 7.1 },
    { title: "我们是不能延期了", score: 7.2 },
    { title: "流星世界演绎者：Badge & Dagger", score: 6.9 },
    { title: "天结迷宫大师", score: 6.7 },
  ],
  "2022": [
    { title: "变态监狱", score: 8.7 },
    { title: "星之终途", score: 7.5 },
    { title: "苍之彼方的四重奏 EXTRA2", score: 8.3 },
    { title: "AMBITIOUS MISSION", score: 7.4 },
    { title: "恋爱成双", score: 6.7 },
    { title: "无法忍耐的处男哥哥和不直率的叛逆妹妹", score: 6.9 },
    { title: "废村少女 ～妖异魅惑的笼之乡～", score: 6.8 },
    { title: "ジュエリー・ハーツ・アカデミア -We will wing wonder world-", score: 7.3 },
    { title: "ハミダシクリエイティブ凸", score: 6.8 },
    { title: "为主人献上圣罗的甜蜜侍奉", score: 6.4 },
    { title: "炽焰天穹", score: 7.2 },
    { title: "恋爱绮谭~不存在的真相~", score: 7.5 },
    { title: "甜蜜夏日", score: 7 },
    { title: "ROLEPLAYER：山掛姐妹的黏膜游戏！", score: 6.2 },
    { title: "与鲨鱼共度的七日间", score: 7 },
    { title: "Dreamin' Her -我梦见了她。-", score: 6.9 },
    { title: "BLACK SHEEP TOWN", score: 8.4 },
    { title: "放学后的灰姑娘2", score: 7.3 },
    { title: "飞鸟会长不肯认输！", score: 6.1 },
    { title: "アンレス・テルミナリア", score: 5.9 },
    { title: "スタディ§ステディ2", score: 6.9 },
    { title: "毎日キスしてロリータ", score: 6.3 },
    { title: "夏之终熄", score: 6.5 },
    { title: "もっと！孕ませ！炎のおっぱい異世界おっぱいメイド学園！", score: 7.4 },
  ],
  "2023": [
    { title: "樱之刻 - 于樱花之森下漫步", score: 8.3 },
    { title: "天使☆嚣嚣 RE-BOOT!", score: 6 },
    { title: "GINKA", score: 5.9 },
    { title: "甜蜜女友2+", score: 8 },
    { title: "Hira Hira Hihiru", score: 7.8 },
    { title: "恋狱～月狂病～ 重制版", score: 7.9 },
    { title: "密语-Silver Snow Sister-", score: 6.5 },
    { title: "纯白交响曲 SANA EDITION", score: 7.6 },
    { title: "候鸟", score: 7.1 },
    { title: "八卦恋爱", score: 6.6 },
    { title: "我的眼睛能看光光！不可知的未来与透视的命运", score: 5.7 },
    { title: "纯白交响曲 Remake for FHD", score: 7.2 },
    { title: "AMBITIOUS MISSION アフターエピソード 1", score: 6.5 },
    { title: "AMBITIOUS MISSION アフターエピソード 2", score: 6.4 },
    { title: "巧克甜恋3", score: 7 },
    { title: "ONE.", score: 6.2 },
    { title: "繁花落舞恋如樱-Re:BIRTH-", score: 6.6 },
    { title: "恋にはあまえが必要です", score: 6.6 },
    { title: "FLIP＊FLOP 〜RAMBLING OVERRUN〜", score: 5.9 },
    { title: "女子宿舍的管理员", score: 5.8 },
    { title: "少女之剑与秘密的协奏曲", score: 6.5 },
    { title: "犹格索托斯的庭院", score: 6.7 },
    { title: "TO･RA･WA･SE ～囚われの偽妃が夢みる初夜～", score: 6.8 },
    { title: "妹と彼女 ～それぞれの選択～", score: 7.1 },
  ],
  "2024": [
    { title: "饿殍：明末千里行", score: 6.3 },
    { title: "美少女万华镜异闻 雪女", score: 6.2 },
    { title: "天选庶民的真命之选", score: 5.3 },
    { title: "少女世界的生存之道", score: 5.9 },
    { title: "播种之谣", score: 7.7 },
    { title: "宝石少女 1st.cut:The Reason She Must Perish", score: 6.8 },
    { title: "贽之匣庭", score: 5.5 },
    { title: "濒死的骑士、于异世界中响彻的绝唱", score: 6 },
    { title: "ラブピカルポッピー！", score: 6.7 },
    { title: "悠刻のファムファタル", score: 6.8 },
    { title: "旭光のマリアージュ", score: 6.8 },
    { title: "圣女不死心", score: 7.1 },
    { title: "夜勤病栋 重制版", score: 6.1 },
    { title: "秘密之恋（伪）", score: 6 },
    { title: "刹那绽放的恋之花火", score: 6.4 },
    { title: "异想魅惑2暮色廻奇谭", score: 6.5 },
    { title: "星之终途后日谈：渺茫希望的日记", score: 7.4 },
    { title: "米塔", score: 7.2 },
    { title: "流星 -a Wish Star-", score: 5.8 },
    { title: "启动世界的理想论 -goodbye world index-", score: 6.9 },
    { title: "梦幻的提尔纳诺", score: 5.4 },
    { title: "アンラベル・トリガー", score: 5.3 },
    { title: "制服女友", score: 5.2 },
    { title: "鏖呪ノ嶼", score: 6.8 },
  ],
};

export default data;
